const countryFlagMap: Record<string, { flag: string; iso: string }> = {
  afghanistan: { flag: "🇦🇫", iso: "AF" },
  albania: { flag: "🇦🇱", iso: "AL" },
  algeria: { flag: "🇩🇿", iso: "DZ" },
  andorra: { flag: "🇦🇩", iso: "AD" },
  angola: { flag: "🇦🇴", iso: "AO" },
  antiguaandbarbuda: { flag: "🇦🇬", iso: "AG" },
  argentina: { flag: "🇦🇷", iso: "AR" },
  armenia: { flag: "🇦🇲", iso: "AM" },
  australia: { flag: "🇦🇺", iso: "AU" },
  austria: { flag: "🇦🇹", iso: "AT" },
  azerbaijan: { flag: "🇦🇿", iso: "AZ" },
  bahamas: { flag: "🇧🇸", iso: "BS" },
  bahrain: { flag: "🇧🇭", iso: "BH" },
  bangladesh: { flag: "🇧🇩", iso: "BD" },
  barbados: { flag: "🇧🇧", iso: "BB" },
  belarus: { flag: "🇧🇾", iso: "BY" },
  belgium: { flag: "🇧🇪", iso: "BE" },
  belize: { flag: "🇧🇿", iso: "BZ" },
  benin: { flag: "🇧🇯", iso: "BJ" },
  bhutan: { flag: "🇧🇹", iso: "BT" },
  bolivia: { flag: "🇧🇴", iso: "BO" },
  bosniaandherzegovina: { flag: "🇧🇦", iso: "BA" },
  botswana: { flag: "🇧🇼", iso: "BW" },
  brazil: { flag: "🇧🇷", iso: "BR" },
  brunei: { flag: "🇧🇳", iso: "BN" },
  bulgaria: { flag: "🇧🇬", iso: "BG" },
  burkinafaso: { flag: "🇧🇫", iso: "BF" },
  burundi: { flag: "🇧🇮", iso: "BI" },
  cabooverde: { flag: "🇨🇻", iso: "CV" },
  cambodia: { flag: "🇰🇭", iso: "KH" },
  cameroon: { flag: "🇨🇲", iso: "CM" },
  canada: { flag: "🇨🇦", iso: "CA" },
  centralafricanrepublic: { flag: "🇨🇫", iso: "CF" },
  chad: { flag: "🇹🇩", iso: "TD" },
  chile: { flag: "🇨🇱", iso: "CL" },
  china: { flag: "🇨🇳", iso: "CN" },
  colombia: { flag: "🇨🇴", iso: "CO" },
  comoros: { flag: "🇰🇲", iso: "KM" },
  congo: { flag: "🇨🇬", iso: "CG" },
  costarica: { flag: "🇨🇷", iso: "CR" },
  croatia: { flag: "🇭🇷", iso: "HR" },
  cuba: { flag: "🇨🇺", iso: "CU" },
  cyprus: { flag: "🇨🇾", iso: "CY" },
  czechia: { flag: "🇨🇿", iso: "CZ" },
  democraticrepublicofthecongo: { flag: "🇨🇩", iso: "CD" },
  denmark: { flag: "🇩🇰", iso: "DK" },
  djibouti: { flag: "🇩🇯", iso: "DJ" },
  dominica: { flag: "🇩🇲", iso: "DM" },
  dominicanrepublic: { flag: "🇩🇴", iso: "DO" },
  ecuador: { flag: "🇪🇨", iso: "EC" },
  egypt: { flag: "🇪🇬", iso: "EG" },
  elsalvador: { flag: "🇸🇻", iso: "SV" },
  equatorialguinea: { flag: "🇬🇶", iso: "GQ" },
  eritrea: { flag: "🇪🇷", iso: "ER" },
  estonia: { flag: "🇪🇪", iso: "EE" },
  eswatini: { flag: "🇸🇿", iso: "SZ" },
  ethiopia: { flag: "🇪🇹", iso: "ET" },
  fiji: { flag: "🇫🇯", iso: "FJ" },
  finland: { flag: "🇫🇮", iso: "FI" },
  france: { flag: "🇫🇷", iso: "FR" },
  gabon: { flag: "🇬🇦", iso: "GA" },
  gambia: { flag: "🇬🇲", iso: "GM" },
  georgia: { flag: "🇬🇪", iso: "GE" },
  germany: { flag: "🇩🇪", iso: "DE" },
  ghana: { flag: "🇬🇭", iso: "GH" },
  greece: { flag: "🇬🇷", iso: "GR" },
  grenada: { flag: "🇬🇩", iso: "GD" },
  guatemala: { flag: "🇬🇹", iso: "GT" },
  guinea: { flag: "🇬🇳", iso: "GN" },
  guineabissau: { flag: "🇬🇼", iso: "GW" },
  guyana: { flag: "🇬🇾", iso: "GY" },
  haiti: { flag: "🇭🇹", iso: "HT" },
  honduras: { flag: "🇭🇳", iso: "HN" },
  hungary: { flag: "🇭🇺", iso: "HU" },
  iceland: { flag: "🇮🇸", iso: "IS" },
  india: { flag: "🇮🇳", iso: "IN" },
  indonesia: { flag: "🇮🇩", iso: "ID" },
  iran: { flag: "🇮🇷", iso: "IR" },
  iraq: { flag: "🇮🇶", iso: "IQ" },
  ireland: { flag: "🇮🇪", iso: "IE" },
  israel: { flag: "🇮🇱", iso: "IL" },
  italy: { flag: "🇮🇹", iso: "IT" },
  jamaica: { flag: "🇯🇲", iso: "JM" },
  japan: { flag: "🇯🇵", iso: "JP" },
  jordan: { flag: "🇯🇴", iso: "JO" },
  kazakhstan: { flag: "🇰🇿", iso: "KZ" },
  kenya: { flag: "🇰🇪", iso: "KE" },
  kiribati: { flag: "🇰🇮", iso: "KI" },
  kuwait: { flag: "🇰🇼", iso: "KW" },
  kyrgyzstan: { flag: "🇰🇬", iso: "KG" },
  laos: { flag: "🇱🇦", iso: "LA" },
  latvia: { flag: "🇱🇻", iso: "LV" },
  lebanon: { flag: "🇱🇧", iso: "LB" },
  lesotho: { flag: "🇱🇸", iso: "LS" },
  liberia: { flag: "🇱🇷", iso: "LR" },
  libya: { flag: "🇱🇾", iso: "LY" },
  liechtenstein: { flag: "🇱🇮", iso: "LI" },
  lithuania: { flag: "🇱🇹", iso: "LT" },
  luxembourg: { flag: "🇱🇺", iso: "LU" },
  madagascar: { flag: "🇲🇬", iso: "MG" },
  malawi: { flag: "🇲🇼", iso: "MW" },
  malaysia: { flag: "🇲🇾", iso: "MY" },
  maldives: { flag: "🇲🇻", iso: "MV" },
  mali: { flag: "🇲🇱", iso: "ML" },
  malta: { flag: "🇲🇹", iso: "MT" },
  marshallislands: { flag: "🇲🇭", iso: "MH" },
  mauritania: { flag: "🇲🇷", iso: "MR" },
  mauritius: { flag: "🇲🇺", iso: "MU" },
  mexico: { flag: "🇲🇽", iso: "MX" },
  micronesia: { flag: "🇫🇲", iso: "FM" },
  moldova: { flag: "🇲🇩", iso: "MD" },
  monaco: { flag: "🇲🇨", iso: "MC" },
  mongolia: { flag: "🇲🇳", iso: "MN" },
  montenegro: { flag: "🇲🇪", iso: "ME" },
  morocco: { flag: "🇲🇦", iso: "MA" },
  mozambique: { flag: "🇲🇿", iso: "MZ" },
  myanmar: { flag: "🇲🇲", iso: "MM" },
  namibia: { flag: "🇳🇦", iso: "NA" },
  nauru: { flag: "🇳🇷", iso: "NR" },
  nepal: { flag: "🇳🇵", iso: "NP" },
  netherlands: { flag: "🇳🇱", iso: "NL" },
  newzealand: { flag: "🇳🇿", iso: "NZ" },
  nicaragua: { flag: "🇳🇮", iso: "NI" },
  niger: { flag: "🇳🇪", iso: "NE" },
  nigeria: { flag: "🇳🇬", iso: "NG" },
  northkorea: { flag: "🇰🇵", iso: "KP" },
  northmacedonia: { flag: "🇲🇰", iso: "MK" },
  norway: { flag: "🇳🇴", iso: "NO" },
  oman: { flag: "🇴🇲", iso: "OM" },
  pakistan: { flag: "🇵🇰", iso: "PK" },
  palau: { flag: "🇵🇼", iso: "PW" },
  palestine: { flag: "🇵🇸", iso: "PS" },
  panama: { flag: "🇵🇦", iso: "PA" },
  papuanewguinea: { flag: "🇵🇬", iso: "PG" },
  paraguay: { flag: "🇵🇾", iso: "PY" },
  peru: { flag: "🇵🇪", iso: "PE" },
  philippines: { flag: "🇵🇭", iso: "PH" },
  poland: { flag: "🇵🇱", iso: "PL" },
  portugal: { flag: "🇵🇹", iso: "PT" },
  qatar: { flag: "🇶🇦", iso: "QA" },
  romania: { flag: "🇷🇴", iso: "RO" },
  russia: { flag: "🇷🇺", iso: "RU" },
  rwanda: { flag: "🇷🇼", iso: "RW" },
  saintkittsandnevis: { flag: "🇰🇳", iso: "KN" },
  saintlucia: { flag: "🇱🇨", iso: "LC" },
  saintvincentandthegrenadines: { flag: "🇻🇨", iso: "VC" },
  samoa: { flag: "🇼🇸", iso: "WS" },
  sanmarino: { flag: "🇸🇲", iso: "SM" },
  saotomeandprincipe: { flag: "🇸🇹", iso: "ST" },
  saudiarabia: { flag: "🇸🇦", iso: "SA" },
  senegal: { flag: "🇸🇳", iso: "SN" },
  serbia: { flag: "🇷🇸", iso: "RS" },
  seychelles: { flag: "🇸🇨", iso: "SC" },
  sierraleone: { flag: "🇸🇱", iso: "SL" },
  singapore: { flag: "🇸🇬", iso: "SG" },
  slovakia: { flag: "🇸🇰", iso: "SK" },
  slovenia: { flag: "🇸🇮", iso: "SI" },
  solomonislands: { flag: "🇸🇧", iso: "SB" },
  somalia: { flag: "🇸🇴", iso: "SO" },
  southafrica: { flag: "🇿🇦", iso: "ZA" },
  southkorea: { flag: "🇰🇷", iso: "KR" },
  southsudan: { flag: "🇸🇸", iso: "SS" },
  spain: { flag: "🇪🇸", iso: "ES" },
  srilanka: { flag: "🇱🇰", iso: "LK" },
  sudan: { flag: "🇸🇩", iso: "SD" },
  suriname: { flag: "🇸🇷", iso: "SR" },
  sweden: { flag: "🇸🇪", iso: "SE" },
  switzerland: { flag: "🇨🇭", iso: "CH" },
  syria: { flag: "🇸🇾", iso: "SY" },
  tajikistan: { flag: "🇹🇯", iso: "TJ" },
  tanzania: { flag: "🇹🇿", iso: "TZ" },
  thailand: { flag: "🇹🇭", iso: "TH" },
  timorleste: { flag: "🇹🇱", iso: "TL" },
  togo: { flag: "🇹🇬", iso: "TG" },
  tonga: { flag: "🇹🇴", iso: "TO" },
  trinidadandtobago: { flag: "🇹🇹", iso: "TT" },
  tunisia: { flag: "🇹🇳", iso: "TN" },
  turkey: { flag: "🇹🇷", iso: "TR" },
  turkmenistan: { flag: "🇹🇲", iso: "TM" },
  tuvalu: { flag: "🇹🇻", iso: "TV" },
  uganda: { flag: "🇺🇬", iso: "UG" },
  ukraine: { flag: "🇺🇦", iso: "UA" },
  unitedarabemirates: { flag: "🇦🇪", iso: "AE" },
  unitedkingdom: { flag: "🇬🇧", iso: "GB" },
  unitedstates: { flag: "🇺🇸", iso: "US" },
  uruguay: { flag: "🇺🇾", iso: "UY" },
  uzbekistan: { flag: "🇺🇿", iso: "UZ" },
  vanuatu: { flag: "🇻🇺", iso: "VU" },
  venezuela: { flag: "🇻🇪", iso: "VE" },
  vietnam: { flag: "🇻🇳", iso: "VN" },
  yemen: { flag: "🇾🇪", iso: "YE" },
  zambia: { flag: "🇿🇲", iso: "ZM" },
  zimbabwe: { flag: "🇿🇼", iso: "ZW" },
};

function normalizeCountry(name: string): string {
  return name.replace(/[^a-z]/gi, "").toLowerCase();
}

export function getCountryFlag(countryName: string): string {
  return countryFlagMap[normalizeCountry(countryName)]?.flag ?? "🏳️";
}

export function getCountryIso(countryName: string): string | null {
  return countryFlagMap[normalizeCountry(countryName)]?.iso ?? null;
}

export function getCountryInfo(countryName: string): { flag: string; iso: string | null } {
  const key = normalizeCountry(countryName);
  const entry = countryFlagMap[key];
  return { flag: entry?.flag ?? "🏳️", iso: entry?.iso ?? null };
}

/** Total UN member states (193 + 2 observer states = 195 widely recognized) */
export const TOTAL_UN_COUNTRIES = 193;
