import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";
import type { ExperienceLevel, SocialPlatform } from "../src/generated/prisma/browser";

async function main() {
  const directUrl = process.env.DATABASE_URL!.replace(":6543", ":5432");
  const adapter = new PrismaPg({ connectionString: directUrl });
  const prisma = new PrismaClient({ adapter });

  let organizer = await prisma.organizer.findFirst();
  if (!organizer) {
    organizer = await prisma.organizer.create({
      data: {
        name: "MUNOS Seed Organizer",
        description: "Default organizer for seed data.",
        website: "https://munos.app",
        email: "seed@munos.app",
      },
    });
    console.log("Created seed organizer");
  }

  const base = new Date(2025, 0, 1);
  const d = (days: number, hour = 9) =>
    new Date(base.getFullYear(), base.getMonth(), base.getDate() + days, hour, 0);

  const IMG = {
    hero1: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1600&q=80",
    hero2: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1600&q=80",
    hall: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1600&q=80",
    debate: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1600&q=80",
    room: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=1600&q=80",
    podium: "https://images.unsplash.com/photo-1519567241046-7f570eee3ce6?w=1600&q=80",
    flags: "https://images.unsplash.com/photo-1505664194779-8beaceb93744?w=1600&q=80",
    crowd: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?w=1600&q=80",
  };

  interface Seed {
    name: string;
    slug: string;
    tagline: string;
    description: string;
    theme: string;
    format: "HYBRID" | "OFFLINE" | "ONLINE";
    difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "EXPERT";
    start: number;
    end: number;
    deadline: number | null;
    fee: number;
    currency: string;
    externalDelegates: boolean;
    capacity: number;
    city: string;
    state: string | null;
    country: string;
    school: string;
    university: string | null;
    website: string;
    instagram: string;
    email: string;
    featured?: boolean;
    logo: string;
    banner: string;
    organizerName: string;
    organizerDesc: string;
    venueName: string;
    venueAddress: string;
    venueLat: number;
    venueLng: number;
    socials: { platform: string; url: string }[];
    committees: {
      name: string;
      topic: string;
      description: string;
      difficulty: string;
      maxDelegates: number;
      countries: [string, number][];
    }[];
    awards: { name: string; description: string }[];
    faqs: { question: string; answer: string }[];
    secretariat: { name: string; role: string }[];
  }

  const conferences: Seed[] = [
    {
      name: "New York Model United Nations",
      slug: "nymun-2025",
      tagline: "The flagship MUN experience in the world's diplomatic capital.",
      description:
        "NYMUN brings delegates to the heart of New York City, just blocks from United Nations Headquarters. With over 2,000 delegates from 60+ countries, NYMUN offers an unparalleled simulation experience featuring traditional UN committees, historical crisis bodies, and innovative ad-hoc simulations.",
      theme: "Strength Through Cooperation",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      start: 55,
      end: 59,
      deadline: 30,
      fee: 175,
      currency: "USD",
      externalDelegates: true,
      capacity: 2000,
      city: "New York",
      state: "New York",
      country: "United States",
      school: "New York University",
      university: "New York University",
      website: "https://www.nymun.org",
      instagram: "https://instagram.com/nymun_official",
      email: "secretariat@nymun.org",
      featured: true,
      logo: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=400&h=400&fit=crop&q=80",
      banner: IMG.hero1,
      organizerName: "NYMUN Secretariat",
      organizerDesc: "The NYMUN Secretariat is a student-run organisation hosting one of the largest university MUN conferences in the United States.",
      venueName: "New York Hilton Midtown",
      venueAddress: "1335 6th Ave, New York, NY 10019",
      venueLat: 40.7638,
      venueLng: -73.9797,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/nymun_official" },
        { platform: "TWITTER", url: "https://twitter.com/nymun_official" },
        { platform: "WEBSITE", url: "https://www.nymun.org" },
      ],
      committees: [
        { name: "United Nations Security Council", topic: "Conflict Prevention in the Sahel Region", description: "Addressing terrorism, governance failures and humanitarian crisis across West Africa.", difficulty: "ADVANCED", maxDelegates: 15, countries: [["France", 1], ["United States", 1], ["Nigeria", 1], ["China", 1]] },
        { name: "United Nations General Assembly", topic: "Reforming the UN Security Council", description: "Debating veto power, permanent membership and equitable representation.", difficulty: "BEGINNER", maxDelegates: 193, countries: [["India", 1], ["Germany", 1], ["Brazil", 1], ["Japan", 1]] },
        { name: "CIA Directorate of Operations", topic: "Cold War Crisis: Berlin 1961", description: "A historical crisis simulation during the construction of the Berlin Wall.", difficulty: "EXPERT", maxDelegates: 30, countries: [["United States", 1], ["Soviet Union", 1], ["United Kingdom", 1], ["France", 1]] },
        { name: "World Health Organization", topic: "Antimicrobial Resistance", description: "Tackling the global threat of drug-resistant infections.", difficulty: "INTERMEDIATE", maxDelegates: 50, countries: [["Switzerland", 1], ["India", 1], ["Kenya", 1], ["Brazil", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Awarded to the single most outstanding delegate per committee." },
        { name: "Outstanding Delegate", description: "Recognises consistent excellence across all sessions." },
        { name: "Honorable Mention", description: "Given to delegates who distinguish themselves in debate." },
        { name: "Best Position Paper", description: "For the strongest written preparation per committee." },
      ],
      faqs: [
        { question: "Can international students attend?", answer: "Absolutely — roughly 35% of delegates travel from outside the United States. Visa invitation letters are available." },
        { question: "What is the dress code?", answer: "Formal business attire for all committee sessions and ceremonies." },
      ],
      secretariat: [
        { name: "Elena Vasquez", role: "Secretary-General" },
        { name: "David Kim", role: "Under-Secretary-General, GA Affairs" },
        { name: "Amara Diallo", role: "Crisis Director" },
      ],
    },
    {
      name: "Tokyo Model United Nations",
      slug: "tmun-2025",
      tagline: "Bridging Asia-Pacific diplomacy through Model United Nations.",
      description:
        "TMUN is Japan's premier Model United Nations conference, held in the heart of Tokyo. Delegates from across the Asia-Pacific region and beyond gather to tackle pressing global issues, from climate change to nuclear non-proliferation, in one of the world's most dynamic cities.",
      theme: "Asia-Pacific Leadership for Global Challenges",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      start: 45,
      end: 48,
      deadline: 20,
      fee: 120,
      currency: "USD",
      externalDelegates: true,
      capacity: 800,
      city: "Tokyo",
      state: "Tokyo",
      country: "Japan",
      school: "University of Tokyo",
      university: "University of Tokyo",
      website: "https://www.tmun.jp",
      instagram: "https://instagram.com/tmun_tokyo",
      email: "info@tmun.jp",
      logo: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400&h=400&fit=crop&q=80",
      banner: IMG.hero2,
      organizerName: "TMUN Association",
      organizerDesc: "The TMUN Association is a student-led organisation at the University of Tokyo promoting international diplomacy education across East Asia.",
      venueName: "University of Tokyo - Yasuda Auditorium",
      venueAddress: "7-chome-3-1 Hongo, Bunkyoku, Tokyo 113-8654",
      venueLat: 35.7126,
      venueLng: 139.762,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/tmun_tokyo" },
        { platform: "WEBSITE", url: "https://www.tmun.jp" },
      ],
      committees: [
        { name: "Disarmament and International Security Committee", topic: "Regulating Lethal Autonomous Weapons Systems", description: "Addressing the legal and ethical framework for autonomous weapons.", difficulty: "ADVANCED", maxDelegates: 80, countries: [["Japan", 1], ["South Korea", 1], ["China", 1], ["Australia", 1]] },
        { name: "UNEP", topic: "Pacific Ocean Plastic Pollution Crisis", description: "A regional approach to marine debris in the Asia-Pacific.", difficulty: "BEGINNER", maxDelegates: 60, countries: [["Japan", 1], ["Philippines", 1], ["Fiji", 1], ["Indonesia", 1]] },
        { name: "Economic and Social Council", topic: "Supply Chain Decarbonisation", description: "Balancing economic growth with climate commitments.", difficulty: "INTERMEDIATE", maxDelegates: 54, countries: [["Japan", 1], ["India", 1], ["Vietnam", 1], ["Germany", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
        { name: "Best Delegation", description: "Awarded to the strongest school delegation overall." },
      ],
      faqs: [
        { question: "Is the conference conducted in English?", answer: "Yes, all committee sessions are conducted in English, though interpretation services are available for the opening ceremony." },
        { question: "Do I need a visa for Japan?", answer: "Many nationalities enter Japan visa-free for short stays. The Secretariat provides invitation letters upon request." },
      ],
      secretariat: [
        { name: "Haruki Tanaka", role: "Secretary-General" },
        { name: "Sakura Watanabe", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Paris Model United Nations",
      slug: "parismun-2025",
      tagline: "Debating global governance in the City of Light.",
      description:
        "ParisMUN offers delegates the opportunity to simulate the United Nations in one of Europe's most iconic cities. Held at venues near UNESCO and the historic Palais des Nations, ParisMUN combines rigorous debate with cultural immersion in the French capital.",
      theme: "Liberty, Equality, Solidarity for the World",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      start: 75,
      end: 78,
      deadline: 50,
      fee: 95,
      currency: "EUR",
      externalDelegates: true,
      capacity: 600,
      city: "Paris",
      state: "Ile-de-France",
      country: "France",
      school: "Sciences Po",
      university: "Sciences Po",
      website: "https://www.parismun.org",
      instagram: "https://instagram.com/parismun",
      email: "secretariat@parismun.org",
      logo: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=400&h=400&fit=crop&q=80",
      banner: IMG.flags,
      organizerName: "ParisMUN Association",
      organizerDesc: "ParisMUN is run by students of Sciences Po, one of Europe's leading universities for political science and international affairs.",
      venueName: "Sciences Po - Amphitheatre Emile Boutmy",
      venueAddress: "27 Rue Saint-Guillaume, 75007 Paris",
      venueLat: 48.8553,
      venueLng: 2.3257,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/parismun" },
        { platform: "WEBSITE", url: "https://www.parismun.org" },
      ],
      committees: [
        { name: "United Nations Educational, Scientific and Cultural Organization", topic: "Protecting Cultural Heritage in Conflict Zones", description: "Safeguarding world heritage sites amid armed conflict and extremism.", difficulty: "ADVANCED", maxDelegates: 40, countries: [["France", 1], ["Iraq", 1], ["Syria", 1], ["Italy", 1]] },
        { name: "UN General Assembly Fourth Committee", topic: "Decolonisation and Self-Determination", description: "Addressing remaining non-self-governing territories.", difficulty: "INTERMEDIATE", maxDelegates: 80, countries: [["France", 1], ["Algeria", 1], ["United Kingdom", 1], ["Papua New Guinea", 1]] },
        { name: "UN Women", topic: "Gender-Based Violence in Conflict Areas", description: "Strengthening international frameworks for women's protection.", difficulty: "BEGINNER", maxDelegates: 50, countries: [["France", 1], ["Rwanda", 1], ["Colombia", 1], ["Japan", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
        { name: "Best Position Paper", description: "Per committee." },
      ],
      faqs: [
        { question: "Can I attend if I don't speak French?", answer: "Yes - all committee sessions are conducted entirely in English." },
      ],
      secretariat: [
        { name: "Camille Dupont", role: "Secretary-General" },
        { name: "Mohammed El-Amin", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Berlin Model United Nations",
      slug: "berlinmun-2026",
      tagline: "Europe's rising star - debate at the crossroads of history.",
      description:
        "BerlinMUN has quickly grown into one of Europe's most exciting MUN conferences. Held in Germany's vibrant capital, the conference leverages Berlin's unique history as a city once divided and now unified to explore themes of peace, diplomacy and international cooperation.",
      theme: "Unity in Diversity: Lessons from Berlin",
      format: "OFFLINE",
      difficulty: "BEGINNER",
      start: 110,
      end: 113,
      deadline: 80,
      fee: 65,
      currency: "EUR",
      externalDelegates: true,
      capacity: 500,
      city: "Berlin",
      state: "Berlin",
      country: "Germany",
      school: "Freie Universitat Berlin",
      university: "Freie Universitat Berlin",
      website: "https://www.berlinmun.de",
      instagram: "https://instagram.com/berlinmun",
      email: "info@berlinmun.de",
      logo: "https://images.unsplash.com/photo-1560969184-10fe8719e047?w=400&h=400&fit=crop&q=80",
      banner: IMG.podium,
      organizerName: "BerlinMUN e.V.",
      organizerDesc: "BerlinMUN e.V. is a registered non-profit promoting international understanding through Model United Nations conferences in Berlin.",
      venueName: "Humboldt University - Main Auditorium",
      venueAddress: "Unter den Linden 6, 10099 Berlin",
      venueLat: 52.5185,
      venueLng: 13.3931,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/berlinmun" },
        { platform: "WEBSITE", url: "https://www.berlinmun.de" },
      ],
      committees: [
        { name: "NATO Council", topic: "Defence Spending and Burden-Sharing", description: "Allied nations debate collective security commitments.", difficulty: "INTERMEDIATE", maxDelegates: 30, countries: [["Germany", 1], ["United States", 1], ["France", 1], ["Turkey", 1]] },
        { name: "UNHCR", topic: "Climate-Induced Displacement in Sub-Saharan Africa", description: "Refugee protection in the context of environmental crisis.", difficulty: "BEGINNER", maxDelegates: 50, countries: [["Germany", 1], ["Kenya", 1], ["Uganda", 1], ["Sweden", 1]] },
        { name: "DISEC", topic: "Space Militarisation and Outer Space Treaty Reform", description: "Arms control beyond Earth's atmosphere.", difficulty: "ADVANCED", maxDelegates: 60, countries: [["United States", 1], ["Russia", 1], ["China", 1], ["India", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Honorable Mention", description: "Per committee." },
      ],
      faqs: [
        { question: "Is BerlinMUN beginner-friendly?", answer: "Yes - BerlinMUN is designed to be accessible to first-time delegates with preparation workshops and mentorship." },
      ],
      secretariat: [
        { name: "Lukas Muller", role: "Secretary-General" },
        { name: "Fatima Al-Hassan", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Nairobi International Model United Nations",
      slug: "nimun-2026",
      tagline: "Africa's premier youth diplomacy conference.",
      description:
        "NIMUN brings together the brightest young minds from across Africa and the world to address the continent's most pressing challenges. Hosted in Kenya's dynamic capital, NIMUN is the largest MUN conference in East Africa and a launchpad for Africa's next generation of leaders.",
      theme: "Africa Rising: Youth Leadership for Continental Transformation",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      start: 130,
      end: 133,
      deadline: 95,
      fee: 45,
      currency: "USD",
      externalDelegates: true,
      capacity: 1000,
      city: "Nairobi",
      state: "Nairobi County",
      country: "Kenya",
      school: "United Nations Office at Nairobi",
      university: null,
      website: "https://www.nimun.org",
      instagram: "https://instagram.com/nimun_ke",
      email: "info@nimun.org",
      logo: "https://images.unsplash.com/photo-1611348524140-53c9a25263d6?w=400&h=400&fit=crop&q=80",
      banner: IMG.crowd,
      organizerName: "NIMUN Association Kenya",
      organizerDesc: "NIMUN Association Kenya is a youth-led non-profit promoting diplomacy and leadership across East Africa through Model United Nations.",
      venueName: "United Nations Office at Nairobi - Gigiri",
      venueAddress: "United Nations Avenue, Nairobi, Kenya",
      venueLat: -1.2329,
      venueLng: 36.8157,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/nimun_ke" },
        { platform: "WEBSITE", url: "https://www.nimun.org" },
      ],
      committees: [
        { name: "African Union Assembly", topic: "AfCFTA Implementation and Regional Integration", description: "Heads of state simulation of the African Continental Free Trade Area.", difficulty: "ADVANCED", maxDelegates: 55, countries: [["Kenya", 1], ["Nigeria", 1], ["South Africa", 1], ["Ethiopia", 1]] },
        { name: "UN Environment Programme", topic: "Green Energy Transition in Developing Nations", description: "Renewable energy access and sustainable development.", difficulty: "BEGINNER", maxDelegates: 80, countries: [["Kenya", 1], ["Morocco", 1], ["India", 1], ["Germany", 1]] },
        { name: "World Health Organization", topic: "Universal Health Coverage in Sub-Saharan Africa", description: "Building resilient health systems on the continent.", difficulty: "INTERMEDIATE", maxDelegates: 60, countries: [["Kenya", 1], ["Rwanda", 1], ["Ghana", 1], ["Senegal", 1]] },
        { name: "UNICEF", topic: "Youth Empowerment and Education Access", description: "Ensuring quality education for every African child.", difficulty: "BEGINNER", maxDelegates: 50, countries: [["Kenya", 1], ["Uganda", 1], ["Tanzania", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
        { name: "Best African Delegation", description: "Awarded to the strongest African school delegation." },
      ],
      faqs: [
        { question: "Is NIMUN open to non-African delegates?", answer: "Yes - NIMUN welcomes delegates from all continents. About 30% of delegates attend from outside Africa." },
      ],
      secretariat: [
        { name: "Wanjiku Mwangi", role: "Secretary-General" },
        { name: "Kwame Asante", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Sydney Model United Nations",
      slug: "symun-2025",
      tagline: "The Southern Hemisphere's flagship MUN conference.",
      description:
        "SYMUN is Australia's largest and most prestigious Model United Nations conference. Held in Sydney's iconic harbour city, delegates from across Oceania and Asia-Pacific engage in high-level debate on issues ranging from Pacific island climate resilience to Indo-Pacific security architecture.",
      theme: "Pacific Voices, Global Impact",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      start: 80,
      end: 83,
      deadline: 55,
      fee: 80,
      currency: "AUD",
      externalDelegates: true,
      capacity: 700,
      city: "Sydney",
      state: "New South Wales",
      country: "Australia",
      school: "University of Sydney",
      university: "University of Sydney",
      website: "https://www.symun.org.au",
      instagram: "https://instagram.com/symun_sydney",
      email: "secretariat@symun.org.au",
      logo: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=400&h=400&fit=crop&q=80",
      banner: IMG.hall,
      organizerName: "SYMUN Society",
      organizerDesc: "The SYMUN Society is the University of Sydney's Model United Nations society, hosting Australia's premier annual MUN conference.",
      venueName: "University of Sydney - Great Hall",
      venueAddress: "Camperdown, NSW 2006, Australia",
      venueLat: -33.8886,
      venueLng: 151.1871,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/symun_sydney" },
        { platform: "WEBSITE", url: "https://www.symun.org.au" },
      ],
      committees: [
        { name: "Pacific Islands Forum", topic: "Climate Migration and Small Island Developing States", description: "Addressing existential climate threats to Pacific island nations.", difficulty: "ADVANCED", maxDelegates: 18, countries: [["Australia", 1], ["Fiji", 1], ["Tuvalu", 1], ["New Zealand", 1]] },
        { name: "UN General Assembly", topic: "Nuclear Non-Proliferation in the Indo-Pacific", description: "Strengthening the global non-proliferation regime.", difficulty: "INTERMEDIATE", maxDelegates: 100, countries: [["Australia", 1], ["Japan", 1], ["India", 1], ["South Korea", 1]] },
        { name: "UNICEF", topic: "Indigenous Youth Rights and Education", description: "Protecting the rights of indigenous children across Oceania.", difficulty: "BEGINNER", maxDelegates: 50, countries: [["Australia", 1], ["New Zealand", 1], ["Papua New Guinea", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
      ],
      faqs: [
        { question: "Do I need a visa for Australia?", answer: "International delegates should check Australia's visa requirements. The Secretariat provides invitation letters for visa applications." },
      ],
      secretariat: [
        { name: "Olivia Chen", role: "Secretary-General" },
        { name: "Jack Thompson", role: "Director-General" },
      ],
    },
    {
      name: "Singapore Model United Nations",
      slug: "smun-2026",
      tagline: "Asia's gateway conference - debate where East meets West.",
      description:
        "SMUN is Southeast Asia's premier Model United Nations conference, hosted in the city-state that sits at the crossroads of global trade and diplomacy. With a focus on multilateral cooperation and innovative policy solutions, SMUN attracts delegates from over 40 countries across the Asia-Pacific.",
      theme: "Multilateralism for the New Era",
      format: "OFFLINE",
      difficulty: "ADVANCED",
      start: 140,
      end: 143,
      deadline: 105,
      fee: 150,
      currency: "SGD",
      externalDelegates: true,
      capacity: 900,
      city: "Singapore",
      state: "Singapore",
      country: "Singapore",
      school: "National University of Singapore",
      university: "National University of Singapore",
      website: "https://www.smun.sg",
      instagram: "https://instagram.com/smun_sg",
      email: "secretariat@smun.sg",
      featured: true,
      logo: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=400&h=400&fit=crop&q=80",
      banner: IMG.room,
      organizerName: "SMUN Society",
      organizerDesc: "The SMUN Society is a student-run organisation at the National University of Singapore promoting international diplomacy and policy innovation.",
      venueName: "Suntec Singapore Convention Centre",
      venueAddress: "1 Raffles Blvd, Singapore 039593",
      venueLat: 1.2953,
      venueLng: 103.8593,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/smun_sg" },
        { platform: "LINKEDIN", url: "https://linkedin.com/company/smun" },
        { platform: "WEBSITE", url: "https://www.smun.sg" },
      ],
      committees: [
        { name: "ASEAN Regional Forum", topic: "South China Sea Territorial Disputes", description: "Navigating sovereignty claims and freedom of navigation.", difficulty: "ADVANCED", maxDelegates: 27, countries: [["Singapore", 1], ["China", 1], ["Vietnam", 1], ["Philippines", 1], ["Japan", 1]] },
        { name: "ECOSOC", topic: "Digital Currency Regulation and Financial Inclusion", description: "Central bank digital currencies and emerging payment systems.", difficulty: "INTERMEDIATE", maxDelegates: 54, countries: [["Singapore", 1], ["China", 1], ["India", 1], ["Sweden", 1]] },
        { name: "UNEP", topic: "Biodiversity Loss in the Coral Triangle", description: "Marine conservation across Southeast Asia's biodiversity hotspot.", difficulty: "BEGINNER", maxDelegates: 50, countries: [["Singapore", 1], ["Indonesia", 1], ["Philippines", 1], ["Malaysia", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
        { name: "Best Position Paper", description: "Per committee." },
      ],
      faqs: [
        { question: "Is SMUN open to high school students?", answer: "SMUN is primarily a university-level conference, though exceptional high school delegates may apply on a case-by-case basis." },
      ],
      secretariat: [
        { name: "Wei Jie Tan", role: "Secretary-General" },
        { name: "Priya Nair", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Toronto International Model United Nations",
      slug: "timun-2025",
      tagline: "Canada's most diverse MUN - unite, debate, inspire.",
      description:
        "TIMUN is Canada's largest international Model United Nations conference, held in the multicultural metropolis of Toronto. Known for its inclusive atmosphere, rigorous academic programme and vibrant social events, TIMUN welcomes delegates from over 50 countries each year.",
      theme: "Diversity as Strength: Inclusive Global Governance",
      format: "OFFLINE",
      difficulty: "BEGINNER",
      start: 60,
      end: 63,
      deadline: 35,
      fee: 75,
      currency: "CAD",
      externalDelegates: true,
      capacity: 1200,
      city: "Toronto",
      state: "Ontario",
      country: "Canada",
      school: "University of Toronto",
      university: "University of Toronto",
      website: "https://www.timun.ca",
      instagram: "https://instagram.com/timun_ca",
      email: "secretariat@timun.ca",
      logo: "https://images.unsplash.com/photo-1517090504332-94f1c2e7de61?w=400&h=400&fit=crop&q=80",
      banner: IMG.crowd,
      organizerName: "TIMUN Society",
      organizerDesc: "The TIMUN Society at the University of Toronto runs Canada's premier international Model United Nations conference annually.",
      venueName: "Metro Toronto Convention Centre",
      venueAddress: "255 Front St W, Toronto, ON M5V 2W6",
      venueLat: 43.6426,
      venueLng: -79.3871,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/timun_ca" },
        { platform: "TWITTER", url: "https://twitter.com/timun_ca" },
        { platform: "WEBSITE", url: "https://www.timun.ca" },
      ],
      committees: [
        { name: "UN Security Council", topic: "Peacekeeping Reform in the 21st Century", description: "Rethinking the mandate, funding and scope of UN peacekeeping operations.", difficulty: "ADVANCED", maxDelegates: 15, countries: [["Canada", 1], ["United States", 1], ["France", 1], ["China", 1], ["Nigeria", 1]] },
        { name: "World Trade Organization", topic: "Intellectual Property and Developing Nations", description: "TRIPS, technology transfer and access to medicines.", difficulty: "INTERMEDIATE", maxDelegates: 40, countries: [["Canada", 1], ["India", 1], ["Brazil", 1], ["Japan", 1]] },
        { name: "UNICEF", topic: "Refugee Education and Youth Resilience", description: "Ensuring continuity of education for displaced children.", difficulty: "BEGINNER", maxDelegates: 60, countries: [["Canada", 1], ["Jordan", 1], ["Lebanon", 1], ["Uganda", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
        { name: "Honorable Mention", description: "Per committee." },
      ],
      faqs: [
        { question: "Is TIMUN suitable for beginners?", answer: "Absolutely - about 40% of delegates are first-timers and we offer a comprehensive preparation guide." },
      ],
      secretariat: [
        { name: "Sophie Martin", role: "Secretary-General" },
        { name: "Raj Patel", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Dubai International MUN Summit",
      slug: "dims-2026",
      tagline: "Where East meets West - diplomacy in the desert.",
      description:
        "The Dubai International MUN Summit brings together delegates from the Middle East, Africa, Asia and Europe for three days of intensive debate. Held in one of the world's most ambitious cities, DIMS explores the intersection of technology, trade and traditional diplomacy.",
      theme: "Innovation Meets Diplomacy",
      format: "HYBRID",
      difficulty: "INTERMEDIATE",
      start: 100,
      end: 102,
      deadline: 70,
      fee: 100,
      currency: "AED",
      externalDelegates: true,
      capacity: 800,
      city: "Dubai",
      state: "Dubai",
      country: "United Arab Emirates",
      school: "American University of Sharjah",
      university: "American University of Sharjah",
      website: "https://www.dims.ae",
      instagram: "https://instagram.com/dims_dubai",
      email: "info@dims.ae",
      logo: "https://images.unsplash.com/photo-1580674285054-bed31e145f59?w=400&h=400&fit=crop&q=80",
      banner: IMG.podium,
      organizerName: "DIMS Secretariat",
      organizerDesc: "DIMS is organised by students of the American University of Sharjah and partners across the Gulf region.",
      venueName: "Dubai International Financial Centre",
      venueAddress: "Gate Village, Building 3, Dubai, UAE",
      venueLat: 25.2148,
      venueLng: 55.275,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/dims_dubai" },
        { platform: "WEBSITE", url: "https://www.dims.ae" },
      ],
      committees: [
        { name: "OPEC Conference", topic: "Energy Transition and Producer Nation Economies", description: "Oil-producing nations navigate the shift to renewable energy.", difficulty: "ADVANCED", maxDelegates: 13, countries: [["UAE", 1], ["Saudi Arabia", 1], ["Iraq", 1], ["Nigeria", 1]] },
        { name: "UN General Assembly", topic: "Water Security in the Middle East and North Africa", description: "Transboundary water management in arid regions.", difficulty: "INTERMEDIATE", maxDelegates: 80, countries: [["UAE", 1], ["Jordan", 1], ["Egypt", 1], ["Israel", 1]] },
        { name: "International Telecommunication Union", topic: "Bridging the Digital Divide", description: "Universal internet access and spectrum allocation.", difficulty: "BEGINNER", maxDelegates: 50, countries: [["UAE", 1], ["India", 1], ["Kenya", 1], ["Germany", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
      ],
      faqs: [
        { question: "Is DIMS fully in-person?", answer: "DIMS is a hybrid conference - all committee sessions are available both in-person and online for virtual delegates." },
      ],
      secretariat: [
        { name: "Khalid Al-Rashid", role: "Secretary-General" },
        { name: "Sarah Johnson", role: "Director-General" },
      ],
    },
    {
      name: "Mumbai Model United Nations",
      slug: "mmun-2025",
      tagline: "South Asia's largest student diplomacy conference.",
      description:
        "MMUN is one of the largest Model United Nations conferences in South Asia, bringing together thousands of delegates from across India and the subcontinent. With a reputation for passionate debate and creative committee formats, MMUN is a cornerstone of the Indian MUN circuit.",
      theme: "India and the World: South-South Cooperation",
      format: "OFFLINE",
      difficulty: "BEGINNER",
      start: 42,
      end: 45,
      deadline: 18,
      fee: 35,
      currency: "USD",
      externalDelegates: true,
      capacity: 2500,
      city: "Mumbai",
      state: "Maharashtra",
      country: "India",
      school: "St. Xavier's College Mumbai",
      university: "University of Mumbai",
      website: "https://www.mmun.in",
      instagram: "https://instagram.com/mmun_mumbai",
      email: "info@mmun.in",
      logo: "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=400&h=400&fit=crop&q=80",
      banner: IMG.debate,
      organizerName: "MMUN Foundation",
      organizerDesc: "The MMUN Foundation is a student-led non-profit promoting diplomacy education across India.",
      venueName: "Bombay Convention & Exhibition Centre",
      venueAddress: "Goregaon East, Mumbai, Maharashtra 400063",
      venueLat: 19.169,
      venueLng: 72.886,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/mmun_mumbai" },
        { platform: "WEBSITE", url: "https://www.mmun.in" },
      ],
      committees: [
        { name: "UN General Assembly", topic: "Global South Debt Sustainability", description: "Addressing sovereign debt crises in developing nations.", difficulty: "BEGINNER", maxDelegates: 150, countries: [["India", 1], ["Sri Lanka", 1], ["Pakistan", 1], ["Bangladesh", 1]] },
        { name: "UNHCR", topic: "Rohingya Crisis and Regional Responsibility", description: "Displacement, humanitarian aid and burden-sharing.", difficulty: "ADVANCED", maxDelegates: 50, countries: [["India", 1], ["Bangladesh", 1], ["Myanmar", 1], ["Japan", 1]] },
        { name: "World Health Organization", topic: "Pandemic Preparedness in South Asia", description: "Strengthening regional health security infrastructure.", difficulty: "INTERMEDIATE", maxDelegates: 60, countries: [["India", 1], ["Bangladesh", 1], ["Nepal", 1], ["Sri Lanka", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
        { name: "Best Indian Delegation", description: "Awarded to the strongest Indian school delegation." },
      ],
      faqs: [
        { question: "Is MMUN beginner-friendly?", answer: "Yes - MMUN is designed to be accessible to first-time delegates with preparation workshops and mentorship." },
      ],
      secretariat: [
        { name: "Ananya Sharma", role: "Secretary-General" },
        { name: "Arjun Gupta", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Copenhagen Climate Model United Nations",
      slug: "ccmun-2026",
      tagline: "The world's only climate-focused MUN conference.",
      description:
        "CCMUN is a unique Model United Nations conference dedicated entirely to climate change, environmental policy and sustainability. Delegates tackle the most pressing ecological challenges of our time in Scandinavia's greenest city, home to the COP15 climate summit.",
      theme: "Climate Justice for All",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      start: 120,
      end: 122,
      deadline: 85,
      fee: 55,
      currency: "EUR",
      externalDelegates: true,
      capacity: 400,
      city: "Copenhagen",
      state: "Capital Region",
      country: "Denmark",
      school: "University of Copenhagen",
      university: "University of Copenhagen",
      website: "https://www.ccmun.dk",
      instagram: "https://instagram.com/ccmun_cph",
      email: "info@ccmun.dk",
      logo: "https://images.unsplash.com/photo-1513622470522-26c3c8a854bc?w=400&h=400&fit=crop&q=80",
      banner: IMG.flags,
      organizerName: "CCMUN Society",
      organizerDesc: "CCMUN Society is a student organisation at the University of Copenhagen dedicated to climate diplomacy education.",
      venueName: "University of Copenhagen - South Campus",
      venueAddress: "Njalsgade 120, 2300 Copenhagen S",
      venueLat: 55.6594,
      venueLng: 12.5903,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/ccmun_cph" },
        { platform: "WEBSITE", url: "https://www.ccmun.dk" },
      ],
      committees: [
        { name: "UNFCCC COP Simulation", topic: "Nationally Determined Contributions 3.0", description: "Negotiating the next generation of climate pledges.", difficulty: "ADVANCED", maxDelegates: 40, countries: [["Denmark", 1], ["China", 1], ["United States", 1], ["India", 1], ["Brazil", 1]] },
        { name: "Green Climate Fund Board", topic: "Loss and Damage Finance", description: "Funding mechanisms for climate-vulnerable nations.", difficulty: "INTERMEDIATE", maxDelegates: 25, countries: [["Denmark", 1], ["Maldives", 1], ["Germany", 1], ["Saudi Arabia", 1]] },
        { name: "Intergovernmental Panel on Climate Change", topic: "Feedback Loops and Tipping Points", description: "Scientific assessment and policy recommendations.", difficulty: "BEGINNER", maxDelegates: 30, countries: [["Denmark", 1], ["Australia", 1], ["Canada", 1], ["Japan", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Best Policy Proposal", description: "For the most innovative and actionable policy solution." },
      ],
      faqs: [
        { question: "Do I need a background in climate science?", answer: "No - comprehensive background guides are provided. The conference is designed to be accessible to all experience levels." },
      ],
      secretariat: [
        { name: "Astrid Johansson", role: "Secretary-General" },
        { name: "Omar Hassan", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Buenos Aires Model United Nations",
      slug: "bamun-2025",
      tagline: "Latin America's premier diplomatic simulation.",
      description:
        "BAMUN brings together delegates from across Latin America and the world to debate the region's most critical issues. Set in the vibrant Argentine capital, BAMUN combines rigorous UN simulation with the rich cultural heritage of South America's most European city.",
      theme: "Voices of the Americas",
      format: "OFFLINE",
      difficulty: "BEGINNER",
      start: 68,
      end: 71,
      deadline: 40,
      fee: 40,
      currency: "USD",
      externalDelegates: true,
      capacity: 600,
      city: "Buenos Aires",
      state: "Buenos Aires",
      country: "Argentina",
      school: "Universidad de Buenos Aires",
      university: "Universidad de Buenos Aires",
      website: "https://www.bamun.org",
      instagram: "https://instagram.com/bamun_ba",
      email: "info@bamun.org",
      logo: "https://images.unsplash.com/photo-1612294037637-ec328d0e075e?w=400&h=400&fit=crop&q=80",
      banner: IMG.hall,
      organizerName: "BAMUN Association",
      organizerDesc: "BAMUN is a student-run organisation at the Universidad de Buenos Aires promoting multilateral diplomacy across Latin America.",
      venueName: "Palacio de Cultura Kirchner",
      venueAddress: "Sarmiento 151, C1042 Buenos Aires",
      venueLat: -34.6036,
      venueLng: -58.3816,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/bamun_ba" },
        { platform: "WEBSITE", url: "https://www.bamun.org" },
      ],
      committees: [
        { name: "Organization of American States", topic: "Migration and Refugees in the Americas", description: "Addressing displacement from Central America and the Caribbean.", difficulty: "INTERMEDIATE", maxDelegates: 35, countries: [["Argentina", 1], ["Mexico", 1], ["Colombia", 1], ["United States", 1]] },
        { name: "Mercosur Parliament", topic: "Regional Economic Integration and Trade", description: "Strengthening Mercosur as a trade bloc.", difficulty: "BEGINNER", maxDelegates: 40, countries: [["Argentina", 1], ["Brazil", 1], ["Uruguay", 1], ["Paraguay", 1]] },
        { name: "UN General Assembly", topic: "Drug Policy Reform in Latin America", description: "Rethinking the global war on drugs from a Latin American perspective.", difficulty: "ADVANCED", maxDelegates: 80, countries: [["Argentina", 1], ["Mexico", 1], ["Colombia", 1], ["Uruguay", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Honorable Mention", description: "Per committee." },
      ],
      faqs: [
        { question: "Will sessions be in Spanish or English?", answer: "All sessions are conducted in English to accommodate international delegates, though Spanish interpretation is available at the opening ceremony." },
      ],
      secretariat: [
        { name: "Valentina Rossi", role: "Secretary-General" },
        { name: "Matias Lopez", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Stockholm Nordic Model United Nations",
      slug: "nordmun-2026",
      tagline: "Nordic values, global perspective.",
      description:
        "NORDMUN is Scandinavia's leading Model United Nations conference, hosted in the Swedish capital. The conference brings a distinctly Nordic lens to global challenges - emphasising consensus-building, human rights and sustainable development - while maintaining the rigour of full UN simulation.",
      theme: "Consensus in a Divided World",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      start: 155,
      end: 158,
      deadline: 120,
      fee: 50,
      currency: "EUR",
      externalDelegates: true,
      capacity: 450,
      city: "Stockholm",
      state: "Stockholm County",
      country: "Sweden",
      school: "Stockholm University",
      university: "Stockholm University",
      website: "https://www.nordmun.se",
      instagram: "https://instagram.com/nordmun_se",
      email: "info@nordmun.se",
      logo: "https://images.unsplash.com/photo-1509356843151-3e7d96241e11?w=400&h=400&fit=crop&q=80",
      banner: IMG.room,
      organizerName: "NORDMUN Society",
      organizerDesc: "NORDMUN Society is a student organisation at Stockholm University promoting Nordic values in international diplomacy.",
      venueName: "Stockholm City Hall",
      venueAddress: "Hantverkargatan 1, 111 44 Stockholm",
      venueLat: 59.3273,
      venueLng: 18.0544,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/nordmun_se" },
        { platform: "WEBSITE", url: "https://www.nordmun.se" },
      ],
      committees: [
        { name: "Nordic Council", topic: "Arctic Resource Management and Indigenous Rights", description: "Balancing development with Sami and Inuit self-determination.", difficulty: "ADVANCED", maxDelegates: 10, countries: [["Sweden", 1], ["Norway", 1], ["Finland", 1], ["Denmark", 1], ["Iceland", 1]] },
        { name: "UN Human Rights Council", topic: "Surveillance States and Digital Privacy", description: "National security vs. civil liberties in the digital age.", difficulty: "INTERMEDIATE", maxDelegates: 47, countries: [["Sweden", 1], ["Germany", 1], ["China", 1], ["United States", 1]] },
        { name: "World Maritime Organization", topic: "Shipping Emissions and Ocean Governance", description: "Decarbonising global maritime transport.", difficulty: "BEGINNER", maxDelegates: 40, countries: [["Sweden", 1], ["Norway", 1], ["Greece", 1], ["Japan", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
      ],
      faqs: [
        { question: "Is Stockholm expensive for delegates?", answer: "We offer affordable accommodation packages through partner hotels. The registration fee includes all sessions and materials." },
      ],
      secretariat: [
        { name: "Erik Lindstrom", role: "Secretary-General" },
        { name: "Ingrid Olsen", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Cairo International Model United Nations",
      slug: "caimun-2025",
      tagline: "Where history meets diplomacy - debate in the land of pharaohs.",
      description:
        "CAIMUN is one of Africa and the Middle East's most established MUN conferences, hosted in Egypt's ancient capital. Delegates explore the intersection of tradition, development and multilateral cooperation in a city that has witnessed millennia of human civilisation.",
      theme: "Heritage, Development and the Global South",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      start: 50,
      end: 53,
      deadline: 25,
      fee: 50,
      currency: "USD",
      externalDelegates: true,
      capacity: 800,
      city: "Cairo",
      state: "Cairo Governorate",
      country: "Egypt",
      school: "American University in Cairo",
      university: "American University in Cairo",
      website: "https://www.caimun.org",
      instagram: "https://instagram.com/caimun_eg",
      email: "info@caimun.org",
      logo: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?w=400&h=400&fit=crop&q=80",
      banner: IMG.podium,
      organizerName: "CAIMUN Society",
      organizerDesc: "CAIMUN is the Model United Nations society of the American University in Cairo, one of the region's leading educational institutions.",
      venueName: "American University in Cairo - Downtown Campus",
      venueAddress: "420 Fifth Avenue, New Cairo 11835",
      venueLat: 30.0236,
      venueLng: 31.4931,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/caimun_eg" },
        { platform: "WEBSITE", url: "https://www.caimun.org" },
      ],
      committees: [
        { name: "Arab League", topic: "Water Scarcity and Transboundary River Disputes", description: "Nile Basin politics and regional water governance.", difficulty: "ADVANCED", maxDelegates: 22, countries: [["Egypt", 1], ["Sudan", 1], ["Ethiopia", 1], ["Kenya", 1]] },
        { name: "UN General Assembly", topic: "Food Security in the MENA Region", description: "Addressing hunger and agricultural transformation.", difficulty: "BEGINNER", maxDelegates: 100, countries: [["Egypt", 1], ["Tunisia", 1], ["Morocco", 1], ["Jordan", 1]] },
        { name: "DISEC", topic: "Counter-Terrorism and Civil Liberties", description: "Balancing security with human rights in the fight against extremism.", difficulty: "INTERMEDIATE", maxDelegates: 60, countries: [["Egypt", 1], ["France", 1], ["Saudi Arabia", 1], ["United States", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
      ],
      faqs: [
        { question: "Is it safe to attend CAIMUN in Cairo?", answer: "Yes - Cairo is a major tourist destination and the conference venue is in a secure area. The Secretariat provides safety guidance." },
      ],
      secretariat: [
        { name: "Nour El-Din", role: "Secretary-General" },
        { name: "Yasmin Hafez", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Seoul International Model United Nations",
      slug: "simun-2026",
      tagline: "Technology, peace and the Korean Peninsula.",
      description:
        "SIMUN is South Korea's premier Model United Nations conference, held in the dynamic capital of Seoul. The conference is uniquely positioned to explore issues of technology governance, Korean Peninsula security and East Asian regional cooperation, leveraging Korea's position as a global technology leader.",
      theme: "Technology for Peace: Innovation in Diplomacy",
      format: "HYBRID",
      difficulty: "INTERMEDIATE",
      start: 145,
      end: 148,
      deadline: 110,
      fee: 110,
      currency: "USD",
      externalDelegates: true,
      capacity: 700,
      city: "Seoul",
      state: "Seoul",
      country: "South Korea",
      school: "Korea University",
      university: "Korea University",
      website: "https://www.simun.kr",
      instagram: "https://instagram.com/simun_seoul",
      email: "info@simun.kr",
      logo: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=400&h=400&fit=crop&q=80",
      banner: IMG.hero2,
      organizerName: "SIMUN Association",
      organizerDesc: "SIMUN Association is a student-led organisation at Korea University promoting diplomacy and technology policy education.",
      venueName: "Korea University - Anam Campus",
      venueAddress: "145 Anam-ro, Seongbuk-gu, Seoul 02841",
      venueLat: 37.5894,
      venueLng: 127.0323,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/simun_seoul" },
        { platform: "TWITTER", url: "https://twitter.com/simun_seoul" },
        { platform: "WEBSITE", url: "https://www.simun.kr" },
      ],
      committees: [
        { name: "Six-Party Talks", topic: "Korean Peninsula Denuclearisation", description: "A multilateral negotiation simulation on nuclear disarmament.", difficulty: "ADVANCED", maxDelegates: 12, countries: [["South Korea", 1], ["North Korea", 1], ["United States", 1], ["China", 1], ["Japan", 1], ["Russia", 1]] },
        { name: "ITU Council", topic: "5G and 6G Spectrum Governance", description: "Managing the next generation of wireless communications.", difficulty: "INTERMEDIATE", maxDelegates: 40, countries: [["South Korea", 1], ["China", 1], ["United States", 1], ["Germany", 1]] },
        { name: "UNICEF", topic: "Digital Child Safety Online", description: "Protecting children in the digital world.", difficulty: "BEGINNER", maxDelegates: 50, countries: [["South Korea", 1], ["Japan", 1], ["Australia", 1], ["Sweden", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
        { name: "Best Position Paper", description: "Per committee." },
      ],
      faqs: [
        { question: "Is SIMUN suitable for beginners?", answer: "Yes - SIMUN offers beginner-friendly committees and comprehensive preparation guides for all delegates." },
      ],
      secretariat: [
        { name: "Ji-Hoon Park", role: "Secretary-General" },
        { name: "Min-Ji Kim", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Zurich Model United Nations",
      slug: "zmun-2025",
      tagline: "Precision diplomacy in the heart of Europe.",
      description:
        "ZMUN offers a boutique MUN experience in Switzerland's most dynamic city. Known for its intimate committee sizes, high-quality debate and stunning Alpine backdrop, ZMUN is a favourite among experienced delegates seeking depth over scale.",
      theme: "Precision in Policy: Small States, Big Ideas",
      format: "OFFLINE",
      difficulty: "ADVANCED",
      start: 90,
      end: 92,
      deadline: 60,
      fee: 90,
      currency: "CHF",
      externalDelegates: true,
      capacity: 300,
      city: "Zurich",
      state: "Zurich",
      country: "Switzerland",
      school: "ETH Zurich",
      university: "ETH Zurich",
      website: "https://www.zmun.ch",
      instagram: "https://instagram.com/zmun_zurich",
      email: "info@zmun.ch",
      logo: "https://images.unsplash.com/photo-1515488764276-beab7607c1e6?w=400&h=400&fit=crop&q=80",
      banner: IMG.flags,
      organizerName: "ZMUN Association",
      organizerDesc: "ZMUN is a student-led organisation at ETH Zurich, one of the world's leading technical universities.",
      venueName: "ETH Zurich - Audimax",
      venueAddress: "Raumstrasse 101, 8092 Zurich",
      venueLat: 47.3763,
      venueLng: 8.548,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/zmun_zurich" },
        { platform: "WEBSITE", url: "https://www.zmun.ch" },
      ],
      committees: [
        { name: "Bank for International Settlements", topic: "Central Bank Digital Currencies and Monetary Sovereignty", description: "The future of money and central bank independence.", difficulty: "EXPERT", maxDelegates: 20, countries: [["Switzerland", 1], ["United States", 1], ["China", 1], ["European Union", 1]] },
        { name: "World Health Organization", topic: "Geneva as Global Health Capital", description: "Strengthening international health governance from its HQ.", difficulty: "ADVANCED", maxDelegates: 35, countries: [["Switzerland", 1], ["Germany", 1], ["France", 1], ["Japan", 1]] },
        { name: "UNHCR", topic: "Ukrainian Refugee Integration in Europe", description: "Long-term solutions for displaced populations.", difficulty: "INTERMEDIATE", maxDelegates: 40, countries: [["Switzerland", 1], ["Poland", 1], ["Germany", 1], ["Ukraine", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
      ],
      faqs: [
        { question: "How selective is ZMUN?", answer: "ZMUN maintains small committee sizes to ensure high-quality debate. We accept applications on a rolling basis until capacity is reached." },
      ],
      secretariat: [
        { name: "Luca Brunner", role: "Secretary-General" },
        { name: "Sophie Keller", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Lagos Model United Nations",
      slug: "lagmun-2026",
      tagline: "West Africa's innovation-driven MUN conference.",
      description:
        "LAGMUN is Nigeria's fastest-growing Model United Nations conference, hosted in Africa's most populous city. Combining the energy of Lagos with rigorous diplomatic simulation, LAGMUN focuses on entrepreneurship, technology and development across the continent.",
      theme: "Innovation, Enterprise and African Development",
      format: "OFFLINE",
      difficulty: "BEGINNER",
      start: 160,
      end: 163,
      deadline: 125,
      fee: 30,
      currency: "USD",
      externalDelegates: true,
      capacity: 800,
      city: "Lagos",
      state: "Lagos State",
      country: "Nigeria",
      school: "University of Lagos",
      university: "University of Lagos",
      website: "https://www.lagmun.org",
      instagram: "https://instagram.com/lagmun_ng",
      email: "info@lagmun.org",
      logo: "https://images.unsplash.com/photo-1611543694807-2a4a0c1e4e8e?w=400&h=400&fit=crop&q=80",
      banner: IMG.crowd,
      organizerName: "LAGMUN Foundation",
      organizerDesc: "LAGMUN Foundation is a youth-led non-profit promoting diplomacy and entrepreneurship across West Africa.",
      venueName: "Eko Hotels & Suites",
      venueAddress: "Adetokunbo Ademola St, Victoria Island, Lagos",
      venueLat: 6.4281,
      venueLng: 3.4219,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/lagmun_ng" },
        { platform: "WEBSITE", url: "https://www.lagmun.org" },
      ],
      committees: [
        { name: "ECOWAS Parliament", topic: "Regional Security and Free Movement", description: "West African economic and political integration.", difficulty: "INTERMEDIATE", maxDelegates: 15, countries: [["Nigeria", 1], ["Ghana", 1], ["Senegal", 1], ["Ivory Coast", 1]] },
        { name: "UN General Assembly", topic: "Youth Unemployment and the Demographic Dividend", description: "Harnessing Africa's youth bulge for economic growth.", difficulty: "BEGINNER", maxDelegates: 100, countries: [["Nigeria", 1], ["Kenya", 1], ["South Africa", 1], ["Egypt", 1]] },
        { name: "UNCTAD", topic: "E-Commerce and Digital Trade in Developing Nations", description: "Bridging the digital trade gap across Africa.", difficulty: "INTERMEDIATE", maxDelegates: 50, countries: [["Nigeria", 1], ["Rwanda", 1], ["Kenya", 1], ["Ghana", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
      ],
      faqs: [
        { question: "Is Lagos safe for international delegates?", answer: "Yes - the conference venue is in a secure area of Victoria Island. The Secretariat provides airport transfers and safety briefings." },
      ],
      secretariat: [
        { name: "Chidinma Okafor", role: "Secretary-General" },
        { name: "Emeka Nwosu", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Vienna International Model United Nations",
      slug: "vimun-2025",
      tagline: "Diplomacy in the city of Mozart and multilateralism.",
      description:
        "VIMUN is Austria's premier Model United Nations conference, held in Vienna - home to the United Nations Office at Vienna, the IAEA and OSCE. Delegates benefit from the city's unique concentration of international organisations and its rich cultural heritage.",
      theme: "Multilateralism in the Heart of Europe",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      start: 85,
      end: 88,
      deadline: 55,
      fee: 70,
      currency: "EUR",
      externalDelegates: true,
      capacity: 500,
      city: "Vienna",
      state: "Vienna",
      country: "Austria",
      school: "University of Vienna",
      university: "University of Vienna",
      website: "https://www.vimun.at",
      instagram: "https://instagram.com/vimun_vienna",
      email: "info@vimun.at",
      logo: "https://images.unsplash.com/photo-1516550135131-fe3dcb0bedc7?w=400&h=400&fit=crop&q=80",
      banner: IMG.hall,
      organizerName: "VIMUN Association",
      organizerDesc: "VIMUN is a student-run organisation at the University of Vienna promoting international diplomacy and Austrian multilateral traditions.",
      venueName: "Vienna International Centre",
      venueAddress: "Wagramer Str. 5, 1400 Vienna",
      venueLat: 48.2347,
      venueLng: 16.4142,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/vimun_vienna" },
        { platform: "WEBSITE", url: "https://www.vimun.at" },
      ],
      committees: [
        { name: "International Atomic Energy Agency", topic: "Nuclear Non-Proliferation and Safeguards", description: "Monitoring and verification in the nuclear age.", difficulty: "ADVANCED", maxDelegates: 35, countries: [["Austria", 1], ["United States", 1], ["Iran", 1], ["Japan", 1]] },
        { name: "OSCE Permanent Council", topic: "Conflict Resolution in Eastern Europe", description: "Organisation for Security and Co-operation in Europe simulation.", difficulty: "INTERMEDIATE", maxDelegates: 57, countries: [["Austria", 1], ["Germany", 1], ["Poland", 1], ["Ukraine", 1]] },
        { name: "UNODC", topic: "Combating Transnational Organised Crime", description: "Narcotics trafficking, cybercrime and human smuggling.", difficulty: "BEGINNER", maxDelegates: 50, countries: [["Austria", 1], ["Colombia", 1], ["Nigeria", 1], ["Italy", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
      ],
      faqs: [
        { question: "Can delegates visit the UN in Vienna?", answer: "Yes - the Secretariat organises guided tours of the Vienna International Centre for all delegates." },
      ],
      secretariat: [
        { name: "Anna Schmidt", role: "Secretary-General" },
        { name: "Thomas Weber", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Online Global Youth MUN",
      slug: "gya-mun-2026",
      tagline: "The world's largest free virtual MUN conference.",
      description:
        "GYA-MUN is the world's largest fully virtual Model United Nations conference, making diplomatic simulation accessible to every young person with an internet connection. With zero fees, sessions across multiple time zones and delegates from 100+ countries, GYA-MUN proves that geography is no barrier to diplomacy.",
      theme: "No Borders, No Barriers",
      format: "ONLINE",
      difficulty: "BEGINNER",
      start: 165,
      end: 168,
      deadline: 150,
      fee: 0,
      currency: "USD",
      externalDelegates: true,
      capacity: 3000,
      city: "Online",
      state: null,
      country: "Global",
      school: "GYA-MUN Foundation",
      university: null,
      website: "https://www.gyamun.org",
      instagram: "https://instagram.com/gyamun",
      email: "info@gyamun.org",
      logo: "https://images.unsplash.com/photo-1516116216624-53e697fedbea?w=400&h=400&fit=crop&q=80",
      banner: IMG.debate,
      organizerName: "GYA-MUN Foundation",
      organizerDesc: "The GYA-MUN Foundation runs the world's largest free virtual Model United Nations conference, making diplomacy accessible to all.",
      venueName: "Virtual Convention Hall",
      venueAddress: "Online via GYA-MUN platform",
      venueLat: 0,
      venueLng: 0,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/gyamun" },
        { platform: "WEBSITE", url: "https://www.gyamun.org" },
      ],
      committees: [
        { name: "UN General Assembly", topic: "Climate Finance for Developing Nations", description: "A welcoming plenary for newcomers to MUN.", difficulty: "BEGINNER", maxDelegates: 193, countries: [["Nigeria", 1], ["Brazil", 1], ["India", 1], ["Germany", 1]] },
        { name: "UNICEF", topic: "Mental Health for Global Youth", description: "Youth mental health in the post-pandemic era.", difficulty: "BEGINNER", maxDelegates: 80, countries: [["Japan", 1], ["South Africa", 1], ["Canada", 1], ["Mexico", 1]] },
        { name: "ECOSOC", topic: "Closing the Global Digital Divide", description: "Technology access as a human right.", difficulty: "BEGINNER", maxDelegates: 60, countries: [["United States", 1], ["India", 1], ["Kenya", 1], ["Sweden", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Best First-Timer", description: "Outstanding newcomer performance." },
      ],
      faqs: [
        { question: "Is GYA-MUN really free?", answer: "Yes - this event is fully free as part of our mission to make MUN accessible to everyone." },
        { question: "What platform do you use?", answer: "Sessions run on the GYA-MUN virtual convention platform, accessible from any modern browser." },
      ],
      secretariat: [
        { name: "Aisha Rahman", role: "Secretary-General" },
        { name: "Carlos Mendez", role: "Director of Technology" },
      ],
    },
    {
      name: "Rome Model United Nations",
      slug: "romemun-2025",
      tagline: "Debate in the Eternal City — where empires once negotiated.",
      description:
        "ROME MUN brings delegates to one of the world's most historically significant cities for a conference that bridges ancient diplomacy with modern multilateralism. Hosted near the UN Food and Agriculture Organization headquarters, the conference explores food security, cultural preservation and Mediterranean cooperation.",
      theme: "Ancient Wisdom, Modern Diplomacy",
      format: "OFFLINE",
      difficulty: "BEGINNER",
      start: 72,
      end: 74,
      deadline: 45,
      fee: 60,
      currency: "EUR",
      externalDelegates: true,
      capacity: 450,
      city: "Rome",
      state: "Lazio",
      country: "Italy",
      school: "Luiss Guido Carli",
      university: "Luiss Guido Carli",
      website: "https://www.romemun.it",
      instagram: "https://instagram.com/romemun",
      email: "info@romemun.it",
      logo: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=400&h=400&fit=crop&q=80",
      banner: IMG.hall,
      organizerName: "ROME MUN Association",
      organizerDesc: "ROME MUN is a student-run organisation at Luiss Guido Carli promoting Mediterranean diplomacy and international cooperation.",
      venueName: "Luiss Guido Carli — Viale Romania",
      venueAddress: "Viale Romania 32, 00197 Roma",
      venueLat: 41.9228,
      venueLng: 12.4947,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/romemun" },
        { platform: "WEBSITE", url: "https://www.romemun.it" },
      ],
      committees: [
        { name: "FAO Conference", topic: "Global Food Systems and Hunger Eradication", description: "Tackling food insecurity from the organisation's home city.", difficulty: "INTERMEDIATE", maxDelegates: 40, countries: [["Italy", 1], ["Brazil", 1], ["India", 1], ["Nigeria", 1]] },
        { name: "UN General Assembly", topic: "Mediterranean Migration Routes", description: "Addressing irregular migration across the Mediterranean Sea.", difficulty: "BEGINNER", maxDelegates: 80, countries: [["Italy", 1], ["Libya", 1], ["Tunisia", 1], ["Greece", 1]] },
        { name: "UNESCO", topic: "Safeguarding World Heritage Sites", description: "Protecting cultural and natural heritage from conflict and climate change.", difficulty: "INTERMEDIATE", maxDelegates: 50, countries: [["Italy", 1], ["Egypt", 1], ["Japan", 1], ["France", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Honorable Mention", description: "Per committee." },
      ],
      faqs: [
        { question: "Do I need to speak Italian?", answer: "No — all sessions are conducted in English. Some social events may include Italian cultural experiences." },
      ],
      secretariat: [
        { name: "Giulia Romano", role: "Secretary-General" },
        { name: "Marco Bianchi", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Mexico City Model United Nations",
      slug: "mcmun-2026",
      tagline: "Latin America's most vibrant diplomatic simulation.",
      description:
        "MCMUN is Mexico's largest Model United Nations conference, hosted in one of the world's most vibrant megacities. The conference brings together delegates from across the Americas to address hemispheric challenges including migration, trade, climate and indigenous rights.",
      theme: "One Americas: Shared Challenges, United Solutions",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      start: 95,
      end: 98,
      deadline: 65,
      fee: 55,
      currency: "USD",
      externalDelegates: true,
      capacity: 900,
      city: "Mexico City",
      state: "Mexico City",
      country: "Mexico",
      school: "Universidad Nacional Autonoma de Mexico",
      university: "UNAM",
      website: "https://www.mcmun.mx",
      instagram: "https://instagram.com/mcmun_mx",
      email: "info@mcmun.mx",
      logo: "https://images.unsplash.com/photo-1585464231875-d9ef1f5ad396?w=400&h=400&fit=crop&q=80",
      banner: IMG.crowd,
      organizerName: "MCMUN Foundation",
      organizerDesc: "MCMUN Foundation is a student-led non-profit promoting diplomacy and multilateralism across Latin America from Mexico City.",
      venueName: "Centro de Convenciones Ciudad de Mexico",
      venueAddress: "Eje Central Lazaro Cardenas 115, Col Juarez, CDMX",
      venueLat: 19.4285,
      venueLng: -99.1553,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/mcmun_mx" },
        { platform: "WEBSITE", url: "https://www.mcmun.mx" },
      ],
      committees: [
        { name: "Organization of American States", topic: "Central American Migration Crisis", description: "Addressing root causes and regional solutions to displacement.", difficulty: "ADVANCED", maxDelegates: 35, countries: [["Mexico", 1], ["Guatemala", 1], ["Honduras", 1], ["United States", 1]] },
        { name: "CITES (Convention on International Trade in Endangered Species)", topic: "Illegal Wildlife Trade in Latin America", description: "Combating trafficking of endangered species.", difficulty: "INTERMEDIATE", maxDelegates: 50, countries: [["Mexico", 1], ["Colombia", 1], ["Peru", 1], ["Ecuador", 1]] },
        { name: "UNICEF", topic: "Indigenous Children's Education Rights", description: "Ensuring equitable education for indigenous communities.", difficulty: "BEGINNER", maxDelegates: 60, countries: [["Mexico", 1], ["Bolivia", 1], ["Peru", 1], ["Guatemala", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
      ],
      faqs: [
        { question: "Will sessions be in Spanish or English?", answer: "All sessions are conducted in English. Spanish interpretation is available for the opening ceremony." },
      ],
      secretariat: [
        { name: "Sofia Hernandez", role: "Secretary-General" },
        { name: "Diego Ramirez", role: "Deputy Secretary-General" },
      ],
    },
    {
      name: "Warsaw Model United Nations",
      slug: "warsawmun-2025",
      tagline: "Central Europe's bridge between East and West.",
      description:
        "WarsawMUN is Poland's premier Model United Nations conference, held in a city that sits at the crossroads of European history. The conference leverages Warsaw's unique position as a bridge between Western and Eastern Europe to explore themes of European integration, energy security and democratic governance.",
      theme: "Bridging Europe: Integration, Security and Democracy",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      start: 92,
      end: 95,
      deadline: 60,
      fee: 45,
      currency: "EUR",
      externalDelegates: true,
      capacity: 550,
      city: "Warsaw",
      state: "Masovia",
      country: "Poland",
      school: "University of Warsaw",
      university: "University of Warsaw",
      website: "https://www.warsawmun.pl",
      instagram: "https://instagram.com/warsawmun",
      email: "info@warsawmun.pl",
      logo: "https://images.unsplash.com/photo-1519197924294-4ba991a11128?w=400&h=400&fit=crop&q=80",
      banner: IMG.room,
      organizerName: "WarsawMUN Society",
      organizerDesc: "WarsawMUN Society is a student organisation at the University of Warsaw promoting European and global diplomacy.",
      venueName: "University of Warsaw — Main Campus",
      venueAddress: "Krakowskie Przedmiescie 26/28, 00-927 Warszawa",
      venueLat: 52.2394,
      venueLng: 21.015,
      socials: [
        { platform: "INSTAGRAM", url: "https://instagram.com/warsawmun" },
        { platform: "WEBSITE", url: "https://www.warsawmun.pl" },
      ],
      committees: [
        { name: "European Council", topic: "Energy Security and the Transition Away from Russian Gas", description: "EU heads of state navigate energy independence.", difficulty: "ADVANCED", maxDelegates: 27, countries: [["Poland", 1], ["Germany", 1], ["France", 1], ["Ukraine", 1]] },
        { name: "OSCE", topic: "Democratic Backsliding in Central and Eastern Europe", description: "Protecting rule of law and civil liberties.", difficulty: "INTERMEDIATE", maxDelegates: 57, countries: [["Poland", 1], ["Hungary", 1], ["Czech Republic", 1], ["Romania", 1]] },
        { name: "NATO Council", topic: "Eastern Flank Defence Posture", description: "Allied defence against hybrid and conventional threats.", difficulty: "INTERMEDIATE", maxDelegates: 30, countries: [["Poland", 1], ["United States", 1], ["United Kingdom", 1], ["Lithuania", 1]] },
      ],
      awards: [
        { name: "Best Delegate", description: "Per committee." },
        { name: "Outstanding Delegate", description: "Per committee." },
      ],
      faqs: [
        { question: "Is WarsawMUN open to non-EU delegates?", answer: "Yes — delegates from all continents are welcome. Poland is part of the Schengen Area for EU visa holders." },
      ],
      secretariat: [
        { name: "Katarzyna Nowak", role: "Secretary-General" },
        { name: "Piotr Kowalski", role: "Deputy Secretary-General" },
      ],
    },
  ];

  let count = 0;
  for (const seed of conferences) {
    const existingConf = await prisma.conference.findUnique({ where: { slug: seed.slug } });
    if (existingConf) {
      console.log(`Skipping (already exists): ${seed.name}`);
      continue;
    }

    const confOrganizer = await prisma.organizer.create({
      data: {
        name: seed.organizerName,
        description: seed.organizerDesc,
        school: seed.school,
        university: seed.university || null,
        website: seed.website,
        email: seed.email,
      },
    });

    const startDate = d(seed.start);
    const endDate = d(seed.end);

    await prisma.conference.create({
      data: {
        slug: seed.slug,
        name: seed.name,
        tagline: seed.tagline,
        description: seed.description,
        theme: seed.theme,
        format: seed.format,
        difficulty: seed.difficulty,
        startDate,
        endDate,
        registrationOpen: seed.deadline === null || d(seed.deadline) > new Date(),
        externalDelegates: seed.externalDelegates,
        fee: seed.fee,
        currency: seed.currency,
        registrationDeadline: seed.deadline !== null ? d(seed.deadline) : null,
        capacity: seed.capacity,
        website: seed.website,
        instagram: seed.instagram,
        email: seed.email,
        school: seed.school,
        university: seed.university || null,
        city: seed.city,
        state: seed.state,
        country: seed.country,
        logoUrl: seed.logo,
        bannerUrl: seed.banner,
        featured: seed.featured ?? false,
        published: true,
        organizerId: confOrganizer.id,
        venue: {
          create: {
            name: seed.venueName,
            address: seed.venueAddress,
            city: seed.city,
            state: seed.state,
            country: seed.country,
            latitude: seed.venueLat,
            longitude: seed.venueLng,
            mapsUrl: `https://www.google.com/maps?q=${encodeURIComponent(seed.venueName + ", " + seed.city)}`,
          },
        },
        socialLinks: {
           create: seed.socials.map((s) => ({ platform: s.platform as SocialPlatform, url: s.url })),
        },
        committees: {
          create: seed.committees.map((c, i) => ({
            name: c.name,
            topic: c.topic,
            description: c.description,
             difficulty: c.difficulty as ExperienceLevel,
            maxDelegates: c.maxDelegates,
            createdAt: new Date(Date.now() + i),
            countryMatrix: {
              create: c.countries.map(([country, seats]) => ({ country, seats })),
            },
          })),
        },
        agenda: {
          create: [
            { title: "Opening Ceremony", description: "Welcome addresses and committee assignments.", startAt: startDate, endAt: new Date(startDate.getTime() + 2 * 3600000), sortOrder: 0 },
            { title: "Committee Session I", description: "Roll call, opening speeches, moderated caucus.", startAt: new Date(startDate.getTime() + 4 * 3600000), endAt: new Date(startDate.getTime() + 7 * 3600000), sortOrder: 100 },
            { title: "Committee Session II", description: "Unmoderated caucus and working papers.", startAt: new Date(startDate.getTime() + 86400000), endAt: new Date(startDate.getTime() + 86400000 + 7 * 3600000), sortOrder: 200 },
            { title: "Committee Session III", description: "Draft resolutions and amendments.", startAt: new Date(startDate.getTime() + 2 * 86400000), endAt: new Date(startDate.getTime() + 2 * 86400000 + 7 * 3600000), sortOrder: 300 },
            { title: "Voting & Awards", description: "Final votes, resolution adoption and award ceremony.", startAt: new Date(endDate.getTime() - 4 * 3600000), endAt: new Date(endDate.getTime() - 2 * 3600000), sortOrder: 400 },
          ],
        },
        brochures: {
          create: {
            title: `${seed.name} Conference Guide`,
            fileName: `${seed.slug}-guide.pdf`,
            mimeType: "application/pdf",
            sizeBytes: 120000,
            fileUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
          },
        },
        gallery: {
          create: [IMG.hero1, IMG.hall, IMG.debate, IMG.room, IMG.flags, IMG.crowd].map((url, i) => ({ url, alt: `Conference photo ${i + 1}`, sortOrder: i })),
        },
        awards: {
          create: seed.awards.map((a, i) => ({ name: a.name, description: a.description, sortOrder: i })),
        },
        faqs: {
          create: seed.faqs.map((f, i) => ({ question: f.question, answer: f.answer, sortOrder: i })),
        },
        secretariat: {
          create: seed.secretariat.map((s, i) => ({ name: s.name, role: s.role, sortOrder: i })),
        },
      },
    });

    count++;
    console.log(`Seeded: ${seed.name}`);
  }

  console.log(`\nDone! ${count} new conferences seeded.`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    process.exit(0);
  });
