import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../src/generated/prisma/client";

async function main() {
  const directUrl = process.env.DATABASE_URL!.replace(":6543", ":5432");
  const adapter = new PrismaPg({ connectionString: directUrl });
  const prisma = new PrismaClient({ adapter });

  // Clear old seed data
  await prisma.conferenceCommittee.deleteMany();
  await prisma.conferenceFaq.deleteMany();
  await prisma.conferenceAward.deleteMany();
  await prisma.secretariat.deleteMany();
  await prisma.conferenceSocialLink.deleteMany();
  await prisma.venue.deleteMany();
  await prisma.conference.deleteMany();
  await prisma.organizer.deleteMany();
  console.log("Cleared old conference data");

  // Create organizers
  const organizers = await Promise.all([
    prisma.organizer.create({ data: { name: "Harvard International Relations Council", website: "https://www.hirc.harvard.edu", email: "hnmun@hirc.harvard.edu" } }),
    prisma.organizer.create({ data: { name: "THIMUN Foundation", website: "https://foundation.thimun.org", email: "info@thimun.org" } }),
    prisma.organizer.create({ data: { name: "YMUN Singapore", website: "https://ymuns.org", email: "info@ymuns.org" } }),
    prisma.organizer.create({ data: { name: "NAMUN Secretariat", website: "https://www.namun.org", email: "external@namun.org" } }),
    prisma.organizer.create({ data: { name: "VMUN Secretariat", website: "https://vmun.com", email: "info@vmun.com" } }),
    prisma.organizer.create({ data: { name: "Delhi MUN", website: "https://delhimun.in", email: "hi@delhimun.in" } }),
    prisma.organizer.create({ data: { name: "ILMUNC India / Big Red Education", website: "https://bigrededucation.com/ivy-league-mun-conference", email: "ilmunc.india@bigrededucation.com" } }),
    prisma.organizer.create({ data: { name: "MUNindia", website: "https://mymun.com/conferences/munindia-2026", email: "info@munindia.org" } }),
    prisma.organizer.create({ data: { name: "Berkeley MUN", website: "https://berkeleymun.com", email: "info@berkeleymun.com" } }),
    prisma.organizer.create({ data: { name: "ChoMUN / University of Chicago", website: "https://uchicagomun.com", email: "info@uchicagomun.com" } }),
    prisma.organizer.create({ data: { name: "UPMUNC / University of Pennsylvania", website: "https://upmunc.upenn.edu", email: "info@upmunc.upenn.edu" } }),
    prisma.organizer.create({ data: { name: "NCSC / Georgetown University", website: "https://ncsc.georgetown.edu", email: "info@ncsc.georgetown.edu" } }),
    prisma.organizer.create({ data: { name: "CMUNNY / Columbia University", website: "https://cmunny.org", email: "info@cmunny.org" } }),
    prisma.organizer.create({ data: { name: "THIMUN Qatar", website: "https://qatar.thimun.org", email: "info@qatar.thimun.org" } }),
    prisma.organizer.create({ data: { name: "NTUMUN / Nanyang Technological University", website: "https://ntumun.org", email: "info@ntumun.org" } }),
    prisma.organizer.create({ data: { name: "SMUN / National University of Singapore", website: "https://singaporemun.org", email: "info@singaporemun.org" } }),
    prisma.organizer.create({ data: { name: "BEIMUN / International School of Beijing", website: "https://beimun.org", email: "info@beimun.org" } }),
    prisma.organizer.create({ data: { name: "AcadeMUN", website: "https://academun.com", email: "info@academun.com" } }),
    prisma.organizer.create({ data: { name: "MUN Vienna", website: "https://munvienna.com", email: "info@munvienna.com" } }),
    prisma.organizer.create({ data: { name: "MUN Malta", website: "https://munmalta.org", email: "info@munmalta.org" } }),
  ]);

  const [hirc, thimunFdn, ymuns, namun, vmun, delhimun, ilmunc, munindia, berkeley, chomun, upmunc, ncs, cmunny, thimunQatar, ntumun, smun, beimun, academun, munvienna, munmalta] = organizers;

  const IMG = {
    hero1: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1600&q=80",
    hero2: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=1600&q=80",
    debate: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1600&q=80",
    flags: "https://images.unsplash.com/photo-1505664194779-8beaceb93744?w=1600&q=80",
    un: "https://images.unsplash.com/photo-1529107386315-e1a2ed48a620?w=1600&q=80",
  };

  interface RealConference {
    name: string;
    slug: string;
    tagline: string;
    description: string;
    theme?: string;
    format: "HYBRID" | "OFFLINE" | "ONLINE";
    difficulty: "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "EXPERT";
    startDays: number;
    endDays: number;
    deadlineDays: number | null;
    fee: number;
    currency: string;
    externalDelegates: boolean;
    capacity: number;
    city: string;
    state: string | null;
    country: string;
    school: string | null;
    university: string | null;
    website: string;
    instagram: string | null;
    email: string;
    featured: boolean;
    logo: string;
    banner: string;
    organizerIdx: number;
    venueName: string;
    venueAddress: string;
    committees: { name: string; topic: string; description: string; difficulty: string; maxDelegates: number }[];
    faqs: { question: string; answer: string }[];
    secretariat: { name: string; role: string }[];
  }

  const now = new Date();
  const d = (days: number) => new Date(now.getFullYear(), now.getMonth(), now.getDate() + days);

  const conferences: RealConference[] = [
    {
      name: "Harvard National Model United Nations",
      slug: "hnmun-2026",
      tagline: "One of the oldest and largest university-level MUN conferences in the world.",
      description: "HNMUN is hosted each February in Boston by the Harvard International Relations Council. It attracts thousands of delegates from around the world and is a cornerstone event in the collegiate MUN circuit. Known for rigorous procedural accuracy, deep substantive debate, and an exceptionally professional staff.",
      theme: "Diplomacy in a Multipolar World",
      format: "OFFLINE",
      difficulty: "ADVANCED",
      startDays: 195,
      endDays: 198,
      deadlineDays: 120,
      fee: 250,
      currency: "USD",
      externalDelegates: true,
      capacity: 3000,
      city: "Boston",
      state: "Massachusetts",
      country: "United States",
      school: null,
      university: "Harvard University",
      website: "https://www.harvardmun.org",
      instagram: "https://instagram.com/harvardmun",
      email: "hnmun@hirc.harvard.edu",
      featured: true,
      logo: IMG.un,
      banner: IMG.hero1,
      organizerIdx: 0,
      venueName: "Boston Marriott Copley Place",
      venueAddress: "110 Huntington Ave, Boston, MA 02116",
      committees: [
        { name: "United Nations Security Council", topic: "Conflict Prevention in the Sahel Region", description: "Addressing terrorism, governance failures and humanitarian crisis across West Africa.", difficulty: "ADVANCED", maxDelegates: 15 },
        { name: "United Nations General Assembly First Committee", topic: "Disarmament and International Security", description: "Debating nuclear non-proliferation, emerging technologies, and arms control.", difficulty: "INTERMEDIATE", maxDelegates: 193 },
        { name: "Historical Crisis Committee", topic: "The Cuban Missile Crisis — October 1962", description: "A historical crisis simulation during the 13-day standoff between the US and Soviet Union.", difficulty: "EXPERT", maxDelegates: 30 },
        { name: "World Health Organization", topic: "Pandemic Preparedness and Response", description: "Strengthening global health systems for future health emergencies.", difficulty: "INTERMEDIATE", maxDelegates: 50 },
      ],
      faqs: [
        { question: "Can international students attend?", answer: "Yes — roughly 40% of delegates travel from outside the United States." },
        { question: "What is the dress code?", answer: "Formal business attire for all committee sessions and ceremonies." },
      ],
      secretariat: [
        { name: "Secretary-General", role: "Secretary-General" },
        { name: "Director-General", role: "Director-General" },
      ],
    },
    {
      name: "THIMUN The Hague 2027",
      slug: "thimun-hague-2027",
      tagline: "The flagship THIMUN conference in The Hague — the gold standard for international MUN.",
      description: "THIMUN The Hague is the original and most prestigious THIMUN conference, held annually in The Hague, Netherlands. Using THIMUN procedure with consensus-based resolution drafting, it brings together 3,000+ delegates from over 100 countries for a week of intense diplomacy.",
      format: "OFFLINE",
      difficulty: "ADVANCED",
      startDays: 195,
      endDays: 199,
      deadlineDays: 120,
      fee: 280,
      currency: "EUR",
      externalDelegates: true,
      capacity: 3500,
      city: "The Hague",
      state: null,
      country: "Netherlands",
      school: null,
      university: null,
      website: "https://www.thimun.org",
      instagram: "https://instagram.com/officialthimun",
      email: "info@thimun.org",
      featured: true,
      logo: IMG.un,
      banner: IMG.flags,
      organizerIdx: 1,
      venueName: "World Forum The Hague",
      venueAddress: "Churchillplein 10, 2517 JW The Hague",
      committees: [
        { name: "United Nations Security Council", topic: "Protection of Civilians in Armed Conflict", description: "Addressing civilian protection in modern warfare.", difficulty: "ADVANCED", maxDelegates: 15 },
        { name: "联合国大会", topic: "Reforming the United Nations", description: "Debating institutional reform and equitable representation.", difficulty: "INTERMEDIATE", maxDelegates: 193 },
        { name: "International Court of Justice", topic: "Advisory Opinion on Climate Change Obligations", description: "Legal proceedings on state obligations under international climate law.", difficulty: "EXPERT", maxDelegates: 15 },
      ],
      faqs: [
        { question: "What procedure does THIMUN use?", answer: "THIMUN uses its own consensus-based procedure, different from North American MUN." },
      ],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "Yale Model United Nations Singapore",
      slug: "ymuns-2026",
      tagline: "Ivy League MUN standards in the heart of Southeast Asia.",
      description: "YMUNS brings Yale-affiliated academic prestige and the competitive spirit of the North American MUN circuit to Singapore. Organized with direct oversight from Yale staff and alumni, it offers a distinct experience blending Ivy League standards with the dynamism of a major Asian hub.",
      format: "OFFLINE",
      difficulty: "ADVANCED",
      startDays: 120,
      endDays: 122,
      deadlineDays: 80,
      fee: 180,
      currency: "USD",
      externalDelegates: true,
      capacity: 800,
      city: "Singapore",
      state: null,
      country: "Singapore",
      school: null,
      university: "Yale-NUS College",
      website: "https://ymuns.org",
      instagram: "https://instagram.com/ymunsingapore",
      email: "info@ymuns.org",
      featured: true,
      logo: IMG.un,
      banner: IMG.hero2,
      organizerIdx: 2,
      venueName: "Yale-NUS College",
      venueAddress: "16 College Avenue West, Singapore 138527",
      committees: [
        { name: "United Nations Security Council", topic: "Maritime Security in the South China Sea", description: "Addressing territorial disputes and freedom of navigation.", difficulty: "ADVANCED", maxDelegates: 15 },
        { name: "World Health Organization", topic: "Antimicrobial Resistance in Southeast Asia", description: "Tackling drug-resistant infections in the region.", difficulty: "INTERMEDIATE", maxDelegates: 40 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "North American Model United Nations",
      slug: "namun-2026",
      tagline: "Canada's longest-running university-level MUN conference — 41st edition.",
      description: "NAMUN is Canada's oldest university MUN conference, held at the University of Toronto. Founded in 1985, it brings together hundreds of delegates from across the globe for three days of immersive committee sessions, crisis simulations, and networking.",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      startDays: 60,
      endDays: 62,
      deadlineDays: 40,
      fee: 123,
      currency: "CAD",
      externalDelegates: true,
      capacity: 400,
      city: "Toronto",
      state: "Ontario",
      country: "Canada",
      school: null,
      university: "University of Toronto",
      website: "https://www.namun.org",
      instagram: "https://instagram.com/namun2026",
      email: "external@namun.org",
      featured: false,
      logo: IMG.un,
      banner: IMG.debate,
      organizerIdx: 3,
      venueName: "University of Toronto",
      venueAddress: "27 King's College Circle, Toronto, ON M5S 1A1",
      committees: [
        { name: "United Nations General Assembly", topic: "Climate Finance for Developing Nations", description: "Mobilizing financial resources for climate action in the Global South.", difficulty: "INTERMEDIATE", maxDelegates: 50 },
        { name: "Crisis Committee", topic: "Black September 1970", description: "Historical crisis simulation of the Jordanian political crisis.", difficulty: "EXPERT", maxDelegates: 25 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "Vancouver Model United Nations",
      slug: "vmun-2026",
      tagline: "Canada's largest student-run MUN conference.",
      description: "VMUN is hosted annually at the Hyatt Regency Vancouver and is one of the largest student-run MUN conferences in Canada. It offers a diverse range of committees from traditional UN bodies to innovative crisis simulations.",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      startDays: 90,
      endDays: 92,
      deadlineDays: 60,
      fee: 325,
      currency: "CAD",
      externalDelegates: true,
      capacity: 1500,
      city: "Vancouver",
      state: "British Columbia",
      country: "Canada",
      school: null,
      university: null,
      website: "https://vmun.com",
      instagram: "https://instagram.com/vancouvermun",
      email: "info@vmun.com",
      featured: false,
      logo: IMG.un,
      banner: IMG.flags,
      organizerIdx: 4,
      venueName: "Hyatt Regency Vancouver",
      venueAddress: "655 Burrard St, Vancouver, BC V6C 2R7",
      committees: [
        { name: "United Nations Security Council", topic: "Peacekeeping Operations in Sub-Saharan Africa", description: "Evaluating the effectiveness of UN peacekeeping missions.", difficulty: "ADVANCED", maxDelegates: 15 },
        { name: "联合国大会", topic: "Global Migration and Refugee Crisis", description: "Addressing the rights and protection of migrants and refugees.", difficulty: "INTERMEDIATE", maxDelegates: 80 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "Delhi MUN 2026",
      slug: "delhi-mun-2026",
      tagline: "India's capital gets its flagship MUN conference.",
      description: "Delhi MUN 2026 is the maiden edition of a conference that draws delegates from every corner of India. Held in New Delhi, it features both traditional UN committees and India-specific committees like AIPPM and IP.",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      startDays: 30,
      endDays: 31,
      deadlineDays: 20,
      fee: 80,
      currency: "INR",
      externalDelegates: true,
      capacity: 500,
      city: "New Delhi",
      state: "Delhi",
      country: "India",
      school: null,
      university: null,
      website: "https://delhimun.in",
      instagram: "https://instagram.com/delhi_mun",
      email: "hi@delhimun.in",
      featured: true,
      logo: IMG.un,
      banner: IMG.hero2,
      organizerIdx: 5,
      venueName: "TBA",
      venueAddress: "New Delhi, India",
      committees: [
        { name: "All India Political Parties Committee", topic: "One Nation, One Election", description: "Debating simultaneous elections in the Indian parliamentary system.", difficulty: "INTERMEDIATE", maxDelegates: 40 },
        { name: "United Nations Security Council", topic: "Indo-Pacific Security Architecture", description: "Addressing regional security challenges in the Indo-Pacific.", difficulty: "ADVANCED", maxDelegates: 15 },
      ],
      faqs: [
        { question: "Who can attend?", answer: "Open to delegates from across India. School and university students welcome." },
      ],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "ILMUNC India 2026",
      slug: "ilmunc-india-2026",
      tagline: "Ivy League MUN comes to India — hosted by UPenn affiliates.",
      description: "ILMUNC India 2026 is brought to India by Big Red Education and supported by Chitkara University. Organized by UPenn undergraduates, it offers world-class MUN experience with scholarships to the flagship ILMUNC Philadelphia conference.",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      startDays: 15,
      endDays: 17,
      deadlineDays: 10,
      fee: 150,
      currency: "INR",
      externalDelegates: true,
      capacity: 600,
      city: "Chandigarh",
      state: "Chandigarh",
      country: "India",
      school: null,
      university: "Chitkara University",
      website: "https://bigrededucation.com/ivy-league-mun-conference",
      instagram: "https://instagram.com/ilmuncindia",
      email: "ilmunc.india@bigrededucation.com",
      featured: true,
      logo: IMG.un,
      banner: IMG.debate,
      organizerIdx: 6,
      venueName: "Chitkara University",
      venueAddress: "Chandigarh-Patiala National Highway, Rajpura, Punjab",
      committees: [
        { name: "United Nations General Assembly", topic: "Artificial Intelligence Governance", description: "Developing international frameworks for AI regulation.", difficulty: "INTERMEDIATE", maxDelegates: 60 },
        { name: "World Bank", topic: "Debt Sustainability in Low-Income Countries", description: "Addressing the growing debt crisis in developing nations.", difficulty: "ADVANCED", maxDelegates: 30 },
      ],
      faqs: [
        { question: "What is the scholarship?", answer: "Best Delegate from each committee receives a 100% registration fee scholarship to ILMUNC Philadelphia." },
      ],
      secretariat: [{ name: "Asher Zemmel", role: "Secretary-General" }],
    },
    {
      name: "MUNindia 2026",
      slug: "munindia-2026",
      tagline: "India's premier online MUN conference.",
      description: "MUNindia is a large-scale online MUN conference open to university students across India and beyond. It offers a accessible way to experience high-quality MUN without travel costs.",
      format: "ONLINE",
      difficulty: "BEGINNER",
      startDays: 45,
      endDays: 47,
      deadlineDays: 30,
      fee: 0,
      currency: "INR",
      externalDelegates: true,
      capacity: 1000,
      city: "Online",
      state: null,
      country: "India",
      school: null,
      university: null,
      website: "https://mymun.com/conferences/munindia-2026",
      instagram: null,
      email: "info@munindia.org",
      featured: false,
      logo: IMG.un,
      banner: IMG.hero1,
      organizerIdx: 7,
      venueName: "Online",
      venueAddress: "Virtual",
      committees: [
        { name: "United Nations General Assembly", topic: "Sustainable Development Goals: Progress and Challenges", description: "Reviewing global progress on the SDGs.", difficulty: "BEGINNER", maxDelegates: 100 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "Berkeley Model United Nations",
      slug: "bmun-2026",
      tagline: "The West Coast's premier university MUN conference.",
      description: "BMUN is hosted annually at UC Berkeley and is one of the most respected university-level MUN conferences on the West Coast. Known for diverse committee offerings and strong academic standards.",
      format: "OFFLINE",
      difficulty: "ADVANCED",
      startDays: 100,
      endDays: 102,
      deadlineDays: 70,
      fee: 200,
      currency: "USD",
      externalDelegates: true,
      capacity: 1200,
      city: "Berkeley",
      state: "California",
      country: "United States",
      school: null,
      university: "University of California, Berkeley",
      website: "https://berkeleymun.com",
      instagram: "https://instagram.com/berkeleymun",
      email: "info@berkeleymun.com",
      featured: false,
      logo: IMG.un,
      banner: IMG.flags,
      organizerIdx: 8,
      venueName: "UC Berkeley Campus",
      venueAddress: "Berkeley, CA 94720",
      committees: [
        { name: "United Nations Security Council", topic: "Cybersecurity and State-Sponsored Hacking", description: "Addressing the growing threat of state-sponsored cyber attacks.", difficulty: "ADVANCED", maxDelegates: 15 },
        { name: "联合国大会", topic: "Outer Space Governance", description: "Establishing norms for responsible behavior in outer space.", difficulty: "INTERMEDIATE", maxDelegates: 60 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "ChoMUN 2026",
      slug: "chomun-2026",
      tagline: "The premier crisis-focused university MUN conference.",
      description: "ChoMUN is hosted by the University of Chicago and is North America's top crisis-focused MUN conference. Known for interconnected crisis ecosystems, fast-paced simulations, and a low delegate-to-staff ratio.",
      format: "OFFLINE",
      difficulty: "EXPERT",
      startDays: 110,
      endDays: 112,
      deadlineDays: 75,
      fee: 180,
      currency: "USD",
      externalDelegates: true,
      capacity: 600,
      city: "Chicago",
      state: "Illinois",
      country: "United States",
      school: null,
      university: "University of Chicago",
      website: "https://uchicagomun.com",
      instagram: "https://instagram.com/chomun",
      email: "info@uchicagomun.com",
      featured: false,
      logo: IMG.un,
      banner: IMG.debate,
      organizerIdx: 9,
      venueName: "University of Chicago",
      venueAddress: "1100 E 58th St, Chicago, IL 60637",
      committees: [
        { name: "Crisis Committee", topic: "The Fall of the Berlin Wall — 1989", description: "A real-time historical crisis simulation during the collapse of the Iron Curtain.", difficulty: "EXPERT", maxDelegates: 25 },
        { name: "Ad-Hoc Committee", topic: "Secretary-General's Cabinet", description: "An innovative committee structure simulating the UN Secretary-General's inner circle.", difficulty: "EXPERT", maxDelegates: 20 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "UPMUNC 2026",
      slug: "upmunc-2026",
      tagline: "The balanced university MUN experience at UPenn.",
      description: "UPMUNC is the University of Pennsylvania's flagship MUN conference, known for its balanced approach combining traditional UN committees with innovative crisis simulations.",
      format: "OFFLINE",
      difficulty: "ADVANCED",
      startDays: 80,
      endDays: 82,
      deadlineDays: 55,
      fee: 190,
      currency: "USD",
      externalDelegates: true,
      capacity: 800,
      city: "Philadelphia",
      state: "Pennsylvania",
      country: "United States",
      school: null,
      university: "University of Pennsylvania",
      website: "https://upmunc.upenn.edu",
      instagram: "https://instagram.com/upmunc",
      email: "info@upmunc.upenn.edu",
      featured: false,
      logo: IMG.un,
      banner: IMG.hero2,
      organizerIdx: 10,
      venueName: "University of Pennsylvania",
      venueAddress: "3451 Walnut St, Philadelphia, PA 19104",
      committees: [
        { name: "United Nations Security Council", topic: "Nuclear Non-Proliferation in the Middle East", description: "Addressing nuclear ambitions and regional security.", difficulty: "ADVANCED", maxDelegates: 15 },
        { name: "European Union Council", topic: "Energy Security and the Green Transition", description: "Debating Europe's path to energy independence.", difficulty: "INTERMEDIATE", maxDelegates: 40 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "NCSC Georgetown 2026",
      slug: "ncsc-georgetown-2026",
      tagline: "The security-focused MUN conference at Georgetown University.",
      description: "NCSC is Georgetown University's premier security-focused MUN conference, drawing delegates interested in defense policy, intelligence, and international security.",
      format: "OFFLINE",
      difficulty: "ADVANCED",
      startDays: 95,
      endDays: 97,
      deadlineDays: 65,
      fee: 175,
      currency: "USD",
      externalDelegates: true,
      capacity: 700,
      city: "Washington",
      state: "DC",
      country: "United States",
      school: null,
      university: "Georgetown University",
      website: "https://ncsc.georgetown.edu",
      instagram: "https://instagram.com/ncscgeorgetown",
      email: "info@ncsc.georgetown.edu",
      featured: false,
      logo: IMG.un,
      banner: IMG.flags,
      organizerIdx: 11,
      venueName: "Georgetown University",
      venueAddress: "3700 O St NW, Washington, DC 20057",
      committees: [
        { name: "United Nations Security Council", topic: "Counter-Terrorism in the Sahel", description: "Addressing the growing jihadist threat in West Africa.", difficulty: "ADVANCED", maxDelegates: 15 },
        { name: "Intelligence Community", topic: "Global Surveillance and Privacy", description: "Balancing national security with civil liberties.", difficulty: "EXPERT", maxDelegates: 20 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "CMUNNY 2026",
      slug: "cmunny-2026",
      tagline: "Columbia University's intense, crisis-focused NYC MUN.",
      description: "CMUNNY is Columbia University's MUN conference, renowned for its intense, small-committee crisis simulations. Its proximity to UN Headquarters inspires timely and relevant committee topics.",
      format: "OFFLINE",
      difficulty: "EXPERT",
      startDays: 75,
      endDays: 77,
      deadlineDays: 50,
      fee: 160,
      currency: "USD",
      externalDelegates: true,
      capacity: 500,
      city: "New York",
      state: "New York",
      country: "United States",
      school: null,
      university: "Columbia University",
      website: "https://cmunny.org",
      instagram: "https://instagram.com/cmunny",
      email: "info@cmunny.org",
      featured: false,
      logo: IMG.un,
      banner: IMG.debate,
      organizerIdx: 12,
      venueName: "Columbia University",
      venueAddress: "116th St & Broadway, New York, NY 10027",
      committees: [
        { name: "Crisis Committee", topic: "The Cuban Missile Crisis", description: "A real-time crisis simulation of the 1962 standoff.", difficulty: "EXPERT", maxDelegates: 20 },
        { name: "Specialized Agency", topic: "International Atomic Energy Agency", description: "Nuclear safeguards and non-proliferation verification.", difficulty: "ADVANCED", maxDelegates: 25 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "THIMUN Qatar 2026",
      slug: "thimun-qatar-2026",
      tagline: "The Middle East's flagship THIMUN conference.",
      description: "THIMUN Qatar is the Middle East flagship of the THIMUN foundation, bringing THIMUN's consensus-based procedure to Doha. It attracts 1,500+ delegates from across the region and beyond.",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      startDays: 130,
      endDays: 133,
      deadlineDays: 90,
      fee: 220,
      currency: "USD",
      externalDelegates: true,
      capacity: 1500,
      city: "Doha",
      state: null,
      country: "Qatar",
      school: null,
      university: null,
      website: "https://qatar.thimun.org",
      instagram: "https://instagram.com/thimunqatar",
      email: "info@qatar.thimun.org",
      featured: true,
      logo: IMG.un,
      banner: IMG.flags,
      organizerIdx: 13,
      venueName: "Qatar National Convention Centre",
      venueAddress: "Doha, Qatar",
      committees: [
        { name: "United Nations General Assembly", topic: "Water Security in the Middle East", description: "Addressing transboundary water disputes and scarcity.", difficulty: "INTERMEDIATE", maxDelegates: 60 },
        { name: "Human Rights Council", topic: "Migration and Human Rights in the Gulf", description: "Examining labor rights and migrant protections.", difficulty: "INTERMEDIATE", maxDelegates: 40 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "NTUMUN 2026",
      slug: "ntumun-2026",
      tagline: "Southeast Asia's largest university-hosted MUN.",
      description: "NTUMUN is hosted by Nanyang Technological University in Singapore and is one of the largest university-hosted MUN conferences in Southeast Asia, known for its wide committee slate and experienced organizers.",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      startDays: 115,
      endDays: 117,
      deadlineDays: 80,
      fee: 150,
      currency: "SGD",
      externalDelegates: true,
      capacity: 1000,
      city: "Singapore",
      state: null,
      country: "Singapore",
      school: null,
      university: "Nanyang Technological University",
      website: "https://ntumun.org",
      instagram: "https://instagram.com/ntumun",
      email: "info@ntumun.org",
      featured: false,
      logo: IMG.un,
      banner: IMG.hero1,
      organizerIdx: 14,
      venueName: "NTU School of Social Sciences",
      venueAddress: "50 Nanyang Ave, Singapore 639798",
      committees: [
        { name: "United Nations Environment Programme", topic: "Plastic Pollution in the Pacific", description: "Addressing the global plastic waste crisis.", difficulty: "INTERMEDIATE", maxDelegates: 50 },
        { name: "Association of Southeast Asian Nations", topic: "South China Sea Disputes", description: "Regional cooperation on maritime territorial issues.", difficulty: "ADVANCED", maxDelegates: 30 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "SMUN 2026",
      slug: "smun-2026",
      tagline: "NUS-backed premier MUN in Singapore.",
      description: "SMUN is backed by the National University of Singapore and is known for balanced committees, strong regional participation, and reliable logistics. It draws delegates from across Asia-Pacific.",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      startDays: 105,
      endDays: 107,
      deadlineDays: 75,
      fee: 140,
      currency: "SGD",
      externalDelegates: true,
      capacity: 800,
      city: "Singapore",
      state: null,
      country: "Singapore",
      school: null,
      university: "National University of Singapore",
      website: "https://singaporemun.org",
      instagram: "https://instagram.com/singaporemun",
      email: "info@singaporemun.org",
      featured: false,
      logo: IMG.un,
      banner: IMG.hero2,
      organizerIdx: 15,
      venueName: "NUS University Hall",
      venueAddress: "21 Lower Kent Ridge Rd, Singapore 119077",
      committees: [
        { name: "United Nations General Assembly", topic: "Digital Divide and Global Equity", description: "Bridging the technology gap between developed and developing nations.", difficulty: "INTERMEDIATE", maxDelegates: 60 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "BEIMUN 2026",
      slug: "beimun-2026",
      tagline: "Beijing's established THIMUN-affiliated conference.",
      description: "BEIMUN is hosted by the International School of Beijing and is one of the longest-running THIMUN-affiliated conferences in East Asia. It uses THIMUN procedure and draws delegates from across China and the region.",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      startDays: 140,
      endDays: 143,
      deadlineDays: 100,
      fee: 200,
      currency: "USD",
      externalDelegates: true,
      capacity: 600,
      city: "Beijing",
      state: null,
      country: "China",
      school: "International School of Beijing",
      university: null,
      website: "https://beimun.org",
      instagram: "https://instagram.com/beimun",
      email: "info@beimun.org",
      featured: false,
      logo: IMG.un,
      banner: IMG.flags,
      organizerIdx: 16,
      venueName: "International School of Beijing",
      venueAddress: "10 Hua Jia Di Nan Da Jie, Chaoyang, Beijing",
      committees: [
        { name: "United Nations General Assembly", topic: "Climate Change and Small Island Developing States", description: "Protecting vulnerable nations from rising sea levels.", difficulty: "INTERMEDIATE", maxDelegates: 50 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "AcadeMUN 2026",
      slug: "academun-2026",
      tagline: "Basel's international MUN conference.",
      description: "AcadeMUN is a university-level MUN conference held in Basel, Switzerland, known for its intimate setting and strong academic focus.",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      startDays: 70,
      endDays: 72,
      deadlineDays: 45,
      fee: 100,
      currency: "CHF",
      externalDelegates: true,
      capacity: 300,
      city: "Basel",
      state: null,
      country: "Switzerland",
      school: null,
      university: "University of Basel",
      website: "https://academun.com",
      instagram: null,
      email: "info@academun.com",
      featured: false,
      logo: IMG.un,
      banner: IMG.hero1,
      organizerIdx: 17,
      venueName: "University of Basel",
      venueAddress: "Petersplatz 1, 4001 Basel",
      committees: [
        { name: "United Nations General Assembly", topic: "Global Health Equity", description: "Ensuring equal access to healthcare worldwide.", difficulty: "INTERMEDIATE", maxDelegates: 40 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "MUN Vienna 2026",
      slug: "mun-vienna-2026",
      tagline: "Diplomacy in the city of international organizations.",
      description: "MUN Vienna is held in one of the world's major diplomatic capitals, offering delegates the chance to debate in the city that hosts the UN, IAEA, and numerous other international organizations.",
      format: "OFFLINE",
      difficulty: "INTERMEDIATE",
      startDays: 75,
      endDays: 77,
      deadlineDays: 50,
      fee: 120,
      currency: "EUR",
      externalDelegates: true,
      capacity: 400,
      city: "Vienna",
      state: null,
      country: "Austria",
      school: null,
      university: null,
      website: "https://munvienna.com",
      instagram: "https://instagram.com/munvienna",
      email: "info@munvienna.com",
      featured: false,
      logo: IMG.un,
      banner: IMG.flags,
      organizerIdx: 18,
      venueName: "Vienna International Centre",
      venueAddress: "Wagramer Str. 5, 1220 Vienna",
      committees: [
        { name: "International Atomic Energy Agency", topic: "Nuclear Safeguards and Verification", description: "Ensuring compliance with nuclear non-proliferation treaties.", difficulty: "ADVANCED", maxDelegates: 30 },
        { name: "United Nations Office on Drugs and Crime", topic: "Transnational Organized Crime", description: "Combating human trafficking and cybercrime.", difficulty: "INTERMEDIATE", maxDelegates: 40 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
    {
      name: "MUN Malta 2026",
      slug: "mun-malta-2026",
      tagline: "Mediterranean diplomacy in the heart of Malta.",
      description: "MUN Malta is a growing conference in the Mediterranean, offering delegates a unique setting to discuss regional and global issues.",
      format: "OFFLINE",
      difficulty: "BEGINNER",
      startDays: 65,
      endDays: 67,
      deadlineDays: 40,
      fee: 80,
      currency: "EUR",
      externalDelegates: true,
      capacity: 250,
      city: "La Valletta",
      state: null,
      country: "Malta",
      school: null,
      university: null,
      website: "https://munmalta.org",
      instagram: "https://instagram.com/munmalta",
      email: "info@munmalta.org",
      featured: false,
      logo: IMG.un,
      banner: IMG.hero2,
      organizerIdx: 19,
      venueName: "The Mediterranean Conference Centre",
      venueAddress: "Erta St, Valletta VLT 1230, Malta",
      committees: [
        { name: "United Nations General Assembly", topic: "Mediterranean Migration", description: "Addressing the migrant crisis in the Mediterranean.", difficulty: "BEGINNER", maxDelegates: 40 },
      ],
      faqs: [],
      secretariat: [{ name: "Secretary-General", role: "Secretary-General" }],
    },
  ];

  let created = 0;
  for (const conf of conferences) {
    const organizer = organizers[conf.organizerIdx];
    const createdConf = await prisma.conference.create({
      data: {
        name: conf.name,
        slug: conf.slug,
        tagline: conf.tagline,
        description: conf.description,
        theme: conf.theme,
        format: conf.format,
        difficulty: conf.difficulty,
        startDate: d(conf.startDays),
        endDate: d(conf.endDays),
        registrationDeadline: conf.deadlineDays ? d(conf.deadlineDays) : null,
        fee: conf.fee,
        currency: conf.currency,
        externalDelegates: conf.externalDelegates,
        capacity: conf.capacity,
        city: conf.city,
        state: conf.state,
        country: conf.country,
        school: conf.school,
        university: conf.university,
        website: conf.website,
        instagram: conf.instagram,
        email: conf.email,
        featured: conf.featured,
        logoUrl: conf.logo,
        bannerUrl: conf.banner,
        published: true,
        registrationOpen: true,
        organizerId: organizer.id,
      },
    });

    // Create venue
    await prisma.venue.create({
      data: {
        conferenceId: createdConf.id,
        name: conf.venueName,
        address: conf.venueAddress,
        city: conf.city,
        country: conf.country,
      },
    });

    // Create committees
    for (const comm of conf.committees) {
      await prisma.conferenceCommittee.create({
        data: {
          conferenceId: createdConf.id,
          name: comm.name,
          topic: comm.topic,
          description: comm.description,
          difficulty: comm.difficulty as "BEGINNER" | "INTERMEDIATE" | "ADVANCED" | "EXPERT",
          maxDelegates: comm.maxDelegates,
        },
      });
    }

    // Create FAQs
    for (const faq of conf.faqs) {
      await prisma.conferenceFaq.create({
        data: {
          conferenceId: createdConf.id,
          question: faq.question,
          answer: faq.answer,
        },
      });
    }

    // Create secretariat
    for (const sec of conf.secretariat) {
      await prisma.secretariat.create({
        data: {
          conferenceId: createdConf.id,
          name: sec.name,
          role: sec.role,
        },
      });
    }

    created++;
    console.log(`Created: ${conf.name}`);
  }

  console.log(`\nDone! Created ${created} real MUN conferences.`);
  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
